mobi/goponents

projects/go-lib/package.json, projects/go-lib/src/lib/components/go-table/go-table-config.ts, projects/go-lib/src/lib/components/go-table/go-table.component.html, projects/go-lib/src/lib/components/go-table/go-table.component.scss, projects/go-lib/src/lib/components/go-table/go-table.component.ts, projects/go-tester/src/app/app.component.ts
Added a `noDataText` property to the `GoTableConfig` class to specify the text to show when there is no data.
For Issue #11
=> Added a 'no-data' state to the go-table

projects/go-tester/src/app/app.module.ts
Previously, we were unable to compile and serve out app from the root directory. The update to this import allows us to do that thing.
=> Updates the import path to allow the app to be served from the root

package-lock.json, package.json
This update includes a few hotfixes to buttons and icons that
should fix a few discrepencies in goponents.
=> Updates the gosheets module to version 0.7.2

projects/go-lib/src/lib/components/go-table/go-table-paging.model.ts, projects/go-lib/src/lib/components/go-table/go-table.component.html, projects/go-lib/src/lib/components/go-table/go-table.component.scss, projects/go-lib/src/lib/components/go-table/go-table.component.ts, projects/go-tester/src/app/app.component.html, projects/go-tester/src/styles.scss
Updated the table component to be designed in a way that follows the design patterns of the Go Design System. Screenshot:
=> Updated table design to be in-line with the Go Design System

projects/go-lib/src/lib/components/go-table/go-table.component.ts, projects/go-tester/src/app/app.component.ts
Sorting when paging is available did not reset the paging to page 1.
=> Fix bug with sorting and paging

projects/go-lib/package.json
This second beta release includes various bugfixes and improvements to tables and buttons.
=> Increments to v1.0.0-beta.2

package-lock.json, package.json, projects/go-lib/package.json, projects/go-lib/src/lib/components/go-table/go-table.component.html, projects/go-lib/src/lib/components/go-table/go-table.component.scss
This give us access to many of the new things included in gosheets.
The styles for our table component are now included in the
gosheets module. This allows us to refactor out styles and template.
=> Refactor table styles

package-lock.json, package.json, projects/go-lib/package.json
=> Update to v1 of gosheets

projects/go-lib/src/lib/components/go-table/go-table-utils.ts, projects/go-tester/src/app/app.component.html
Bugfix for empty table column Fixes #53
=> [Bugfix] Empty Table Column Errors

.travis.yml, package-lock.json, package.json, tslint.json
This updates a few modules and configures our linter to extend off of the tslint-angular config.
=> Updates linter modules and configuration

projects/go-lib/src/lib/components/go-card/go-card.component.spec.ts
Includes just a couple of basic tests for the card component since it doesn't really do anything.
=> Add tests to card component

projects/go-lib/src/lib/animations/search.animation.ts, projects/go-lib/src/lib/components/go-search/go-search.component.html, projects/go-lib/src/lib/components/go-search/go-search.component.scss, projects/go-lib/src/lib/components/go-search/go-search.component.spec.ts, projects/go-lib/src/lib/components/go-search/go-search.component.ts, projects/go-lib/src/lib/components/go-search/go-search.module.ts, projects/go-lib/src/lib/components/go-search/go-search.service.ts, projects/go-lib/src/lib/go-shared.module.ts, projects/go-lib/src/public_api.ts, projects/go-tester/src/app/app.component.html, projects/go-tester/src/app/app.component.ts, projects/go-tester/src/app/app.module.ts, projects/go-tester/src/app/app.service.ts, projects/go-tester/src/app/components/search-test.component.html, projects/go-tester/src/app/components/search-test.component.ts
https://mobi.teamwork.com/#tasks/13648494
This component is to be used in the header to provide a consistent, global, search.
This should be rendered in the root component insides the `go-header`
```
<go-search>
<search-dummy-results></search-dummy-results>
</go-search>
```
Component file for `<search-dummy-results>`:
```
this.searchService.searchTerm.subscribe(searchTerm => {
// this section is dependent upon what the data looks like
this.appService
.getMockSearch(searchTerm)
.subscribe(results => {
if (results.length === 0) {
this.results = null;
this.searchService.notFoundResponse();
} else {
this.results = results;
this.searchService.successResponse();
}
});
});
}
```
=> [Feature] Search Component

projects/go-lib/src/lib/components/go-modal/go-modal.component.scss, projects/go-lib/src/lib/components/go-off-canvas/go-off-canvas.component.scss, projects/go-lib/src/lib/components/go-search/go-search.component.scss, projects/go-lib/src/lib/components/go-side-nav/go-side-nav/go-side-nav.component.scss, projects/go-lib/src/lib/components/go-toaster/go-toaster.component.scss, projects/go-lib/src/styles/_mixins.scss
Fixes #80 
Adds z-index values for our layout
=> Z-index mappings

projects/go-lib/src/lib/components/go-toast/go-toast.component.spec.ts, projects/go-lib/src/lib/components/go-toast/go-toast.component.ts
This adds basic unit tests around the <go-toast> component and it's corresponding template.
=> Go Toast Tests

package-lock.json, package.json, projects/go-lib/src/lib/components/go-icon-button/go-icon-button.component.html, projects/go-lib/src/lib/components/go-layout/go-layout.component.scss, projects/go-lib/src/lib/components/go-search/go-search.component.scss, projects/go-lib/src/lib/components/go-side-nav/go-nav-group/go-nav-group.component.html, projects/go-lib/src/lib/components/go-side-nav/go-nav-group/go-nav-group.component.scss, projects/go-lib/src/lib/components/go-side-nav/go-nav-item/go-nav-item.component.html, projects/go-lib/src/lib/components/go-table/go-table.component.html, projects/go-tester/browserslist, projects/go-tester/src/app/app.component.ts, projects/go-tester/src/polyfills.ts
Many IE bugs
Squashed them all
=> Bug ie edge cases

projects/go-lib/src/lib/components/go-button/go-button.component.spec.ts, projects/go-lib/src/lib/components/go-button/go-button.component.ts, projects/go-tester/karma.conf.js
This removes kjhtml from the karma config because that node module
has been removed.
This adds basic unit tests around buttons. It additionally tests
some of the basic side effects that the data has on the go-button
template.
=> Test button component

projects/go-lib/src/lib/components/go-header/go-header.component.html, projects/go-lib/src/lib/components/go-header/go-header.component.scss, projects/go-lib/src/lib/components/go-header/go-header.component.ts, projects/go-lib/src/lib/components/go-layout/go-layout.component.scss, projects/go-lib/src/lib/components/go-search/go-search.component.scss, projects/go-lib/src/lib/components/go-search/go-search.component.ts, projects/go-tester/src/app/app.component.html
Screenshot on mobile:
Closes: #84
=> Implemented styles and functionality for a mobile layout

projects/go-lib/src/lib/components/go-accordion/go-accordion-panel.component.scss, projects/go-lib/src/lib/components/go-accordion/go-accordion.component.html, projects/go-lib/src/lib/components/go-accordion/go-accordion.component.ts, projects/go-lib/src/lib/components/go-action-sheet/go-action-sheet.component.html, projects/go-lib/src/lib/components/go-action-sheet/go-action-sheet.component.scss, projects/go-lib/src/lib/components/go-action-sheet/go-action-sheet.component.spec.ts, projects/go-lib/src/lib/components/go-action-sheet/go-action-sheet.component.ts, projects/go-lib/src/lib/components/go-action-sheet/go-action-sheet.module.ts, projects/go-lib/src/lib/components/go-action-sheet/go-panel/go-panel.component.html, projects/go-lib/src/lib/components/go-action-sheet/go-panel/go-panel.component.scss, projects/go-lib/src/lib/components/go-action-sheet/go-panel/go-panel.component.spec.ts, projects/go-lib/src/lib/components/go-action-sheet/go-panel/go-panel.component.ts, projects/go-lib/src/lib/go-shared.module.ts, projects/go-lib/src/public_api.ts, projects/go-tester/src/app/app.component.html, projects/go-tester/src/app/app.component.ts, projects/go-tester/src/app/app.module.ts, projects/go-tester/src/app/components/test-page-2/test-page-2.component.html, projects/go-tester/src/app/components/test-page-2/test-page-2.component.ts
This PR adds action sheets to goponents.
=> Go action sheet

README.md, package.json
This project houses a set of UI components for Angular and designed around the 'Go' design system.
1. Take a look at our [code of conduct](https://github.com/mobi/goponents/blob/master/CODE_OF_CONDUCT.md)
2. Take a look at our [contribution guidelines](https://github.com/mobi/goponents/blob/master/CONTRIBUTING.md)
3. Install the latest version of npm
```bash
npm install -g npm@latest
```
or if you are using `nvm` you can alternatively run:
```bash
nvm install-latest-npm
```
_We try to stay as up to date a possible._
4. Install all of the node modules
```bash
npm install
```
5. Start a development test server:
```bash
ng serve
```
_This will serve the go-tester directory at `localhost:4200`_
6. In a separate tab, start the tests for the go-lib components:
```bash
ng test go-lib
```
_Test …
=> Updates README

CONTRIBUTING.md, README.md
Closes #62
_**Note:** The guide for contributing to this repo is based on the [contribution guide for Angular](https://github.com/angular/angular/blob/master/CONTRIBUTING.md) itself. Parts of this guide were taken verbatim and were originally written by many [fine Angular contributors](https://github.com/angular/angular/blame/master/CONTRIBUTING.md)_
Please read and follow our [Code of conduct](https://github.com/mobi/goponents/blob/master/CODE_OF_CONDUCT.md).
Feel free to open up [an issue](https://github.com/mobi/goponents/issues/new/choose) using the appropriate template.
When any sort of issue is created, depending on the impact or urgency of the issue, one of our [contributors](https://github.com/mobi/goponents/graphs/contributors) will respond as quickly as appropriate on the issue …
=> Adds contribution guide

.github/ISSUE_TEMPLATE/--feature-request.md
Please provide a clear and concise description of what the feature is and how it will be used.
_**Example:**_
> We have a need for [...] 
A clear and concise description of what you want to see built.
_**Example:**_
> This feature will needs to have the following requirements:
> 1. Requirement
> 2. Requirement
=> Update feature request template to be better suited to our needs

.github/ISSUE_TEMPLATE/--chore-or-maintenance-request.md, .github/ISSUE_TEMPLATE/--feature-request.md
_A clear and concise description of the chore or maintenance task._
> We need [...] upgraded or think that [...] could be refactored because it will improve [...].
_Insert a list of requirements or recommendations._
1. [...]
2. [...]
3. [...]
=> Update issue templates

projects/go-lib/src/lib/components/go-badge/go-badge.component.html, projects/go-lib/src/lib/components/go-badge/go-badge.component.scss, projects/go-lib/src/lib/components/go-badge/go-badge.component.spec.ts, projects/go-lib/src/lib/components/go-badge/go-badge.component.ts, projects/go-lib/src/lib/components/go-badge/go-badge.module.ts, projects/go-lib/src/lib/go-shared.module.ts, projects/go-lib/src/public_api.ts, projects/go-tester/src/app/app.component.html, projects/go-tester/src/app/app.module.ts, projects/go-tester/src/app/components/test-page-2/test-page-2.component.html
This adds a badge component to be used with buttons and icons. If we need to use it outside of those components we should do some more testing around this as those are the only two things that I tested this with.
=> [Feature] Go Badge

projects/go-lib/package.json
Let's get a beta release out so we can start testing implementation and getting the documentation ready for the final release.
I think we still have a few bugs to work out, but we can work those out while we document things.
=> Increment the package to v1.2.0-beta.1

.sass-lint.yml, package-lock.json, package.json
Rules copied from gosheets
Also added a pre-commit hook to prevent files from being commited without passing the linter.
fixes #147
=> Add sass-lint

projects/go-lib/src/lib/components/go-button/go-button.component.html, projects/go-lib/src/lib/components/go-button/go-button.component.scss, projects/go-lib/src/lib/components/go-button/go-button.component.spec.ts, projects/go-lib/src/lib/components/go-button/go-button.component.ts, projects/go-lib/src/lib/components/go-datepicker/go-calendar.component.ts, projects/go-lib/src/lib/components/go-datepicker/go-datepicker.component.ts, projects/go-lib/src/lib/components/go-icon/go-icon.component.html, projects/go-lib/src/lib/components/go-icon/go-icon.component.scss, projects/go-lib/src/lib/components/go-icon/go-icon.component.spec.ts, projects/go-lib/src/lib/components/go-icon/go-icon.component.ts
View encapsulation was causing some of our button styles to not
be applied. This moves the styles out of the button component and
into the icon component so that they apply to the correct component.
Previously, we used functions inside the template to declare the
classes on both the icon and button components. Switching this to
use lifecycle hooks and a simple object increases performance.
There are potential cases where the ngOnDestroy lifecycle hook
could be fired when a subscription doesn't exist. This causes the
unsubscribe function to fail and was throwing errors in our tests.
Checking for a subscription in those lifecycle hooks fixes the
issue.
=> Fix button icon alignment

projects/go-lib/src/lib/components/go-select/go-select.component.html, projects/go-lib/src/lib/components/go-select/go-select.component.spec.ts, projects/go-lib/src/lib/components/go-select/go-select.component.ts, projects/go-tester/src/app/components/test-page-3/test-page-3.component.html
This adds a label to the go-select component.
closes #174
=> Go Select Label

projects/go-lib/src/lib/components/go-off-canvas/go-off-canvas.component.scss
Fixes issue #178 where a horizontal scrollbar was appearing for off-canvas component.
=> Fix horizontal overflow in off-canvas window. Closes #178

projects/go-lib/src/lib/components/go-loader/go-loader.component.scss, projects/go-lib/src/lib/components/go-loader/go-loader.component.ts
We needed a light and dark option for the loader. Closes #192 
Added light and dark options to the loader component.
=> [Chore] Added light and dark options to loader

projects/go-lib/src/styles/_variables.scss
We did not have a way to achieve a 20% width column. Closes #155 
Added a column size of 20.
=> [Chore] Adds a 20% Column to the Grid

projects/go-lib/src/lib/components/go-side-nav/go-nav-item/go-nav-item.component.scss, projects/go-tester/src/app/app-routing.module.ts, projects/go-tester/src/app/app.component.ts, projects/go-tester/src/app/app.module.ts, projects/go-tester/src/app/components/test-page-4/test-page-4.component.html, projects/go-tester/src/app/components/test-page-4/test-page-4.component.ts
Closes #162, the height of the active indicator in the navigation was too tall.
Shortened it to a more adequate height.
=> Adjusted height of indicator in nav

README.md
Updates the README to be relevant for all changes made in the `v1.2.1` release.
=> [Chore] Update README v1.2.1

projects/go-lib/src/lib/components/go-side-nav/go-nav-item/go-nav-item.component.html, projects/go-lib/src/lib/components/go-side-nav/go-nav-item/go-nav-item.component.scss, projects/go-lib/src/lib/components/go-side-nav/nav-item.model.ts, projects/go-tester/src/app/app.component.ts
This PR introduces the ability to support external links in the side nav.
Closes: https://github.com/mobi/goponents/issues/211
=> [Feature] Side Nav External Links

projects/go-lib/src/styles/_reset.scss, projects/go-lib/src/styles/styles.scss
Adds [Eric Meyers' CSS Reset](https://meyerweb.com/eric/tools/css/reset/).
fixes #154
=> Add css reset to base styles

projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/select-docs/select-docs.component.html, projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/select-docs/select-docs.component.ts, projects/go-style-guide/src/app/features/ui-kit/components/form-docs/form-docs.component.ts, projects/go-style-guide/src/app/features/ui-kit/routes/ui-kit-routing.module.ts, projects/go-style-guide/src/app/features/ui-kit/ui-kit.module.ts
This adds documentation around the go-select component.
=> Add go-select documentation

projects/go-lib/src/lib/components/go-action-sheet/go-action-sheet.component.scss, projects/go-style-guide/src/app/app.component.ts, projects/go-style-guide/src/app/features/ui-kit/components/action-sheet-docs/action-sheet-docs.component.html, projects/go-style-guide/src/app/features/ui-kit/components/action-sheet-docs/action-sheet-docs.component.ts, projects/go-style-guide/src/app/features/ui-kit/components/action-sheet-docs/components/action-sheet-overview/action-sheet-overview.component.html, projects/go-style-guide/src/app/features/ui-kit/components/action-sheet-docs/components/action-sheet-overview/action-sheet-overview.component.ts, projects/go-style-guide/src/app/features/ui-kit/components/action-sheet-docs/components/action-sheet-panel-docs/action-sheet-panel-docs.component.html, projects/go-style-guide/src/app/features/ui-kit/components/action-sheet-docs/components/action-sheet-panel-docs/action-sheet-panel-docs.component.ts, projects/go-style-guide/src/app/features/ui-kit/routes/ui-kit-routing.module.ts, projects/go-style-guide/src/app/features/ui-kit/ui-kit.module.ts
Because no one knows how to use the action sheet.
Because it explains how to use the action sheet.
Fixes #253
=> [Chore] Action Sheet Documentation

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md, PULL_REQUEST_TEMPLATE
Current PR template was asking for basic information.
New PR template asks for additional information
N/A
=> Move + update PR template

projects/go-style-guide/src/app/app.component.ts, projects/go-style-guide/src/app/features/ui-kit/components/icon-button-docs/icon-button-docs.component.html, projects/go-style-guide/src/app/features/ui-kit/components/icon-button-docs/icon-button-docs.component.spec.ts, projects/go-style-guide/src/app/features/ui-kit/components/icon-button-docs/icon-button-docs.component.ts, projects/go-style-guide/src/app/features/ui-kit/routes/ui-kit-routing.module.ts, projects/go-style-guide/src/app/features/ui-kit/ui-kit.module.ts
closes #219 
This adds documentation for our GoIconButton component.
=> Icon Button Documentation

projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/datepicker-docs/datepicker-docs.component.ts, projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/input-docs/input-docs.component.ts, projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/select-docs/select-docs.component.ts, projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/switch-toggle-docs/switch-toggle-docs.component.html, projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/switch-toggle-docs/switch-toggle-docs.component.ts, projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/text-area-docs/text-area-docs.component.ts, projects/go-style-guide/src/app/features/ui-kit/components/form-docs/form-docs.component.ts, projects/go-style-guide/src/app/features/ui-kit/routes/ui-kit-routing.module.ts, projects/go-style-guide/src/app/features/ui-kit/ui-kit.module.ts
We did not have documentation for the switch toggle component.
Added documentation for the switch toggle component.
Closes #223
=> [Chore] Switch Toggle Documentation

projects/go-style-guide/src/app/shared/components/sub-nav/sub-nav.component.scss
=> [Bugfix] Overflow Hidden on Style Guide Subnav

projects/go-style-guide/src/app/shared/components/sub-nav/sub-nav.component.scss
=> Revert "[Bugfix] Overflow Hidden on Style Guide Subnav"

projects/go-style-guide/src/app/shared/components/sub-nav/sub-nav.component.scss
=> Fixed issue with overflow hidden on subnav style guide

projects/go-lib/src/lib/components/go-table/go-table.component.html, projects/go-lib/src/lib/components/go-table/go-table.component.scss
Closes #238 
We need to make it so that the background of a table row changes when it is selected.
=> Update selected state background of table rows

projects/go-lib/src/lib/components/go-file-upload/go-file-upload.component.html, projects/go-lib/src/lib/components/go-file-upload/go-file-upload.component.spec.ts, projects/go-lib/src/lib/components/go-file-upload/go-file-upload.component.ts
Issue Number: https://github.com/mobi/goponents/issues/308
Depending on how we're getting the files (dragging and dropping vs clicking on the upload) the events from the html come with different attributes. This fixes the attribute properties for clicking on the upload
Fixes #308
=> File Upload Files Undefined

projects/go-lib/src/lib/components/go-checkbox/go-checkbox.component.html, projects/go-lib/src/lib/components/go-checkbox/go-checkbox.component.ts, projects/go-lib/src/styles/_forms.scss, projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/checkbox-docs/checkbox-docs.component.html, projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/checkbox-docs/checkbox-docs.component.ts, projects/go-tester/src/app/components/test-page-3/test-page-3.component.html, projects/go-tester/src/app/components/test-page-3/test-page-3.component.ts
Closes #235 
We need to update the design of our `go-checkbox` to meet the design spec, seen here: https://tangoe.invisionapp.com/dsm/tangoe/tangoe-ds/folder/components/5d3b2fd34b5f2e3140d29587
=> Update checkbox design

projects/go-lib/src/lib/components/go-table/go-table.component.scss
Closes #237 
We need to add striping to the rows of our `go-table`.
=> Add row striping to go-table

projects/go-lib/src/lib/components/go-toast/go-toast.component.ts, projects/go-lib/src/lib/components/go-toaster/go-toaster.component.html, projects/go-lib/src/lib/components/go-toaster/go-toaster.component.ts, projects/go-lib/src/lib/components/go-toaster/go-toaster.service.spec.ts, projects/go-lib/src/lib/components/go-toaster/go-toaster.service.ts, projects/go-style-guide/src/app/features/ui-kit/components/toast-docs/toast-docs.component.html
Issue Number: https://github.com/mobi/goponents/issues/295
When a user hovers over a toast, the toast will cancel the timer until the user hovers off of the toast and then the timer is restarted
=> Pause Toaster On Hover

projects/go-lib/src/lib/components/go-table/go-table-config.model.ts, projects/go-lib/src/lib/components/go-table/go-table.component.spec.ts, projects/go-lib/src/lib/components/go-table/go-table.component.ts, projects/go-style-guide/src/app/features/ui-kit/components/table-docs/components/table-selection/table-selection.component.html, projects/go-style-guide/src/app/features/ui-kit/components/table-docs/components/table-selection/table-selection.component.ts
Issue Number: https://github.com/mobi/goponents/issues/298
There is an option in the table config called preselected. When set to true all rows in the table are set to checked when the table is rendered.
=> Preselect All Options On go-table

projects/go-lib/src/lib/animations/table-details.animation.ts, projects/go-lib/src/lib/components/go-table/go-table.component.html, projects/go-lib/src/lib/components/go-table/go-table.component.scss, projects/go-lib/src/lib/components/go-table/go-table.component.spec.ts, projects/go-lib/src/lib/components/go-table/go-table.component.ts, projects/go-lib/src/lib/components/go-table/go-table.module.ts, projects/go-style-guide/src/app/features/ui-kit/components/table-docs/components/table-details/table-details-test.component.html, projects/go-style-guide/src/app/features/ui-kit/components/table-docs/components/table-details/table-details-test.component.ts, projects/go-style-guide/src/app/features/ui-kit/components/table-docs/components/table-details/table-details.component.html, projects/go-style-guide/src/app/features/ui-kit/components/table-docs/components/table-details/table-details.component.ts, projects/go-style-guide/src/app/features/ui-kit/components/table-docs/table-docs.component.ts, projects/go-style-guide/src/app/features/ui-kit/routes/ui-kit-routing.module.ts, projects/go-style-guide/src/app/features/ui-kit/ui-kit.module.ts
This adds the ability to use details within a table row. The implementor can provide a template
which is then used on every row to show the details when toggled on.
Fixes #250
=> Table Row Details

projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/select-docs/select-docs.component.html
There is a typo in our select docs
This fixes the typo
=> Typo in Select Docs

projects/go-style-guide/src/app/features/ui-kit/components/table-docs/components/table-details/table-details.component.ts
The documentation is showing an incorrect way to implement the `goTableDetails`
Updated the docs to show the correct way to implement table details.
=> Incorrect Docs on Table Details

projects/go-lib/src/lib/components/go-accordion/go-accordion-panel.component.scss, projects/go-lib/src/lib/components/go-accordion/go-accordion-panel.component.spec.ts, projects/go-lib/src/lib/components/go-accordion/go-accordion-panel.component.ts, projects/go-lib/src/lib/components/go-accordion/go-accordion.component.spec.ts, projects/go-lib/src/lib/components/go-accordion/go-accordion.component.ts, projects/go-style-guide/src/app/features/ui-kit/components/accordion-docs/components/accordion-overview/accordion-overview.component.html, projects/go-style-guide/src/app/features/ui-kit/components/accordion-docs/components/accordion-overview/accordion-overview.component.ts, projects/go-style-guide/src/app/shared/components/sub-nav/sub-nav.component.html
Issue Number: https://github.com/mobi/goponents/issues/311
A new option was introduced to support `box-shadow` within the accordion. Using this along with the already created `borderless` option will provide users with a "card" like experience. 
N/A
=> [Feature] Ability to use an Accordion as a card

projects/go-lib/src/lib/components/go-button/go-button.component.scss, projects/go-lib/src/lib/components/go-select/go-select.component.scss, projects/go-lib/src/lib/components/go-switch-toggle/go-switch-toggle.component.scss, projects/go-lib/src/styles/_forms.scss, projects/go-lib/src/styles/_variables.scss, projects/go-style-guide/src/app/features/standards/components/colors/colors.component.html, projects/go-style-guide/src/app/features/standards/components/colors/colors.component.scss, projects/go-style-guide/src/app/features/standards/components/colors/colors.component.ts
Currently we do not have a 'positive' color.
Closes #249 
A 'positive' color has been added for various component.
There shouldn't be, however, if the `ui-color-positive` variable was used outside of Goponents, then that color will now be represented by 'Earth'.
=> [Chore] Add Earth Color

projects/go-lib/src/lib/components/go-table/go-table.component.spec.ts, projects/go-lib/src/lib/components/go-table/go-table.component.ts
When using server side pagination the page specific buttons on the pagination seem broken and don't update the table properly.
When using server side pagination the table emits the correct offset changes from clicking on a specific page.
=> Pagination Bugfix

projects/go-lib/src/lib/components/go-select/go-select.component.scss
Styles for go-select don't include the ng-select styles that are imported
Issue Number: #193 
Use the scss file from ng-select
=> Fix go select styles

projects/go-style-guide/src/app/features/ui-kit/components/table-docs/components/table-column-docs/table-column-docs.component.html, projects/go-style-guide/src/app/features/ui-kit/components/table-docs/components/table-column-docs/table-column-docs.component.spec.ts, projects/go-style-guide/src/app/features/ui-kit/components/table-docs/components/table-column-docs/table-column-docs.component.ts, projects/go-style-guide/src/app/features/ui-kit/components/table-docs/table-docs.component.ts, projects/go-style-guide/src/app/features/ui-kit/routes/ui-kit-routing.module.ts, projects/go-style-guide/src/app/features/ui-kit/ui-kit.module.ts
Issue Number: https://github.com/mobi/goponents/issues/312
No existing documentation for `go-table-column`.
Documentation added for `go-table-column`
N/A
=> Add documentation for go-table-column

.travis.yml
We currently only run `ng test` for the travis build
We will now run an `ng build` of go-lib, then run `ng test`
=> [Chore] Run build of go-lib to travis

projects/go-lib/src/lib/components/go-side-nav/go-side-nav/go-side-nav.service.ts
When the layout is initialized there is a js error with can't call .segments on undefined
There is no error when the page is initialized
=> Undefined Error on Sidenav

projects/go-lib/src/lib/components/go-table/go-table.component.spec.ts, projects/go-lib/src/lib/components/go-table/go-table.component.ts
Issue Number: https://github.com/mobi/goponents/issues/215
All data is now rendered when pagination is off.
N/A
=> [Bugfix] go-table without pagination does not render all data

projects/go-style-guide/src/app/features/ui-kit/components/basic-test/basic-test.component.html, projects/go-style-guide/src/app/features/ui-kit/components/basic-test/basic-test.component.ts
Our off canvas in the docs uses html inputs with labels instead of using the go-input component.
This updates the off canvas to use the go-input component to be consistent with other areas of our style-guide
=> Update Inputs In Off Canvas

projects/go-style-guide/src/app/features/ui-kit/components/copy-docs/copy-docs.component.spec.ts
There is a copy and paste error in the copy doc tests
The copy doc tests have the correct wording
=> Fix Copy and Paste Error in Copy Doc Tests

projects/go-lib/src/lib/components/go-table/go-table.component.scss
**N/A** ~~Tests for the changes have been added (for bug fixes / features)~~
**N/A** ~~Docs have been added / updated (for bug fixes / features)~~
The active indicator for which page you're on in the `go-table` page controls is currently the `positive` color, it should be the `primary` color.
Updated the color to be the `primary` color.
=> Chore table page number active color

projects/go-lib/src/lib/components/go-datepicker/calendar-views.scss, projects/go-lib/src/lib/components/go-datepicker/day-view/go-calendar-day-view.component.html, projects/go-lib/src/lib/components/go-datepicker/go-calendar.component.scss, projects/go-lib/src/lib/components/go-datepicker/go-datepicker.component.ts, projects/go-lib/src/lib/components/go-datepicker/locale-format.ts, projects/go-lib/src/lib/components/go-datepicker/month-view/go-calendar-month-view.component.html, projects/go-lib/src/lib/components/go-datepicker/month-view/go-calendar-month-view.component.ts, projects/go-lib/src/lib/components/go-datepicker/year-view/go-calendar-year-view.component.html, projects/go-lib/src/lib/components/go-datepicker/year-view/go-calendar-year-view.component.spec.ts, projects/go-lib/src/lib/components/go-datepicker/year-view/go-calendar-year-view.component.ts, projects/go-lib/src/lib/components/go-icon-button/go-icon-button.component.scss, projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/datepicker-docs/datepicker-docs.component.html, projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/datepicker-docs/datepicker-docs.component.ts
Issue Number: https://github.com/mobi/goponents/issues/248
Updates the Styles of the datepicker to be more inline with the dsm
=> Update Datepicker Styles

projects/go-lib/src/lib/components/go-hint/go-hint.component.html, projects/go-lib/src/lib/components/go-hint/go-hint.component.scss
Issue Number: https://github.com/mobi/goponents/issues/370
Styles are inline with the DSM
=> Updates Form Hint Styles

projects/go-lib/src/lib/components/go-layout/go-layout.component.html, projects/go-lib/src/lib/components/go-layout/go-layout.component.ts
Issue Number: https://github.com/mobi/goponents/issues/325
When going to a new page the scroll with be reset to the top of the page. When going back to the previous route the scroll is set to the scroll position that they left the page at.
=> Fix Scroll Position on Navigation

README.md, package.json, projects/go-lib/package.json, projects/go-style-guide/src/app/features/ui-kit/components/button-docs/button-docs.component.html
Current README and package.json are describing v1.3.x
Updated both README and package.json to reflect changes introduced in v1.4.0
Also added missing text to a `go-button` in the docs that was missing.
=> [Chore] Update README & package.json for v1.4.0

projects/go-lib/src/lib/components/go-table/go-table.component.spec.ts, projects/go-lib/src/lib/components/go-table/go-table.component.ts
We currently are missing unit tests for many of the methods in the go-table component
This adds unit tests for all public methods in the go-table component
=> Adds unit tests for go-table component

projects/go-lib/src/lib/components/go-datepicker/go-datepicker.component.spec.ts, projects/go-lib/src/lib/components/go-datepicker/go-datepicker.component.ts
Date picker control was being update but display value was not.
Issue Number: https://github.com/mobi/goponents/issues/402
Display value is updated per value change.
N/A
=> [Bug] Fix change detection bug in date picker 

projects/go-lib/src/lib/components/go-modal/go-modal.component.html, projects/go-lib/src/lib/components/go-modal/go-modal.component.spec.ts, projects/go-lib/src/lib/components/go-modal/go-modal.component.ts
Issue Number: https://github.com/mobi/goponents/issues/404
Logic for backdrop clicks was not always accurately differentiating between outside click and inside click.
Backdrop clicks now detected as expected. Method name renamed for clarity. 
N/A
=> [Big] Fix table pagination closing modal (modal backdrop issue)

projects/go-lib/src/lib/components/go-input/go-input.component.html, projects/go-lib/src/lib/components/go-input/go-input.component.scss, projects/go-lib/src/lib/components/go-input/go-input.component.ts
Issue Number: #401
Go Input no longer starts at a minimum width in some cases.
=> [Bug] Go Input Width Sizing Incorrect

projects/go-lib/src/lib/components/go-icon-button/go-icon-button.component.spec.ts, projects/go-lib/src/lib/components/go-icon-button/go-icon-button.component.ts
Issue Number: https://github.com/mobi/goponents/issues/387
There are unit tests around the go-icon-button
This also adds more strict type checking on ButtonSize for the icon button
It shouldn't unless people are using the buttonSize for unintended purposes
=> Button Icon Unit Tests

projects/go-lib/src/lib/components/go-toast/go-toast.component.scss, projects/go-lib/src/styles/_forms.scss, projects/go-lib/src/styles/_hints.scss, projects/go-lib/src/styles/_variables.scss, projects/go-style-guide/src/styles/_settings.scss, projects/go-style-guide/src/styles/_typography.scss, projects/go-tester/src/styles.scss
Issue Number: #346 
The form input are now styled according to the DSM spec.
I introduced a new variable `$weight-medium` set to 500, in accordance with the DSM here: https://tangoe.invisionapp.com/dsm/tangoe/tangoe-ds/asset/fonts/5cd2c07d7a19a658ed12493e. I also added loading those font weights from google fonts in both the app-tester and style guide.
=> Form label styles

projects/go-lib/src/lib/components/go-select/go-select.component.html, projects/go-lib/src/lib/components/go-select/go-select.component.ts, projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/select-docs/select-docs.component.html, projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/select-docs/select-docs.component.ts
Issue Number: https://github.com/mobi/goponents/issues/374
Select items can be grouped by a property that exists on each item.
=> Go Select Group By

projects/go-lib/src/lib/components/go-hint/go-hint.component.spec.ts, projects/go-lib/src/lib/components/go-side-nav/go-nav-group/go-nav-group.component.spec.ts, projects/go-lib/src/lib/components/go-side-nav/go-nav-item/go-nav-item.component.spec.ts, projects/go-lib/src/lib/components/go-side-nav/go-side-nav/go-side-nav.component.spec.ts, projects/go-lib/src/lib/components/go-side-nav/go-side-nav/go-side-nav.service.spec.ts
Issue Number: https://github.com/mobi/goponents/issues/385
There are unit tests for the sidenav components and service
=> Unit Tests for SideNav

projects/go-lib/src/lib/components/go-select/go-select.component.html, projects/go-lib/src/lib/components/go-select/go-select.component.ts, projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/select-docs/select-docs.component.html, projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/select-docs/select-docs.component.ts
Issue Number: https://github.com/mobi/goponents/issues/375
We can pass a custom template into the go-select with using `#goSelectOption` and `#goSelectLabel`
=> Go Select Custom Template

projects/go-lib/src/lib/components/go-table/go-table-column.component.ts, projects/go-lib/src/lib/components/go-table/go-table-config.model.ts, projects/go-lib/src/lib/components/go-table/go-table-search-config.model.ts, projects/go-lib/src/lib/components/go-table/go-table.component.html, projects/go-lib/src/lib/components/go-table/go-table.component.scss, projects/go-lib/src/lib/components/go-table/go-table.component.spec.ts, projects/go-lib/src/lib/components/go-table/go-table.component.ts, projects/go-lib/src/lib/components/go-table/go-table.module.ts, projects/go-style-guide/src/app/features/ui-kit/components/table-docs/components/table-column-docs/table-column-docs.component.html, projects/go-style-guide/src/app/features/ui-kit/components/table-docs/components/table-column-docs/table-column-docs.component.ts, projects/go-style-guide/src/app/features/ui-kit/components/table-docs/components/table-searching/table-searching.component.html, projects/go-style-guide/src/app/features/ui-kit/components/table-docs/components/table-searching/table-searching.component.ts, projects/go-style-guide/src/app/features/ui-kit/components/table-docs/table-docs.component.ts, projects/go-style-guide/src/app/features/ui-kit/routes/ui-kit-routing.module.ts, projects/go-style-guide/src/app/features/ui-kit/ui-kit.module.ts
Issue Number: https://github.com/mobi/goponents/issues/360
A search field can be enabled on a table through the tableConfig
=> Table Search Bar

projects/go-lib/src/lib/components/go-icon/go-icon.component.scss, projects/go-style-guide/src/app/features/ui-kit/components/icon-docs/icon-docs.component.html, projects/go-style-guide/src/app/features/ui-kit/components/icon-docs/icon-docs.component.ts
The documentation for the `iconModifier` binding of our `go-icon` is inaccurate.
Issue Number: #406 
Update the docs to accurately explain how to use the `iconModifier` binding.
=> Update go-icon iconModifier documentation

README.md, projects/go-lib/package.json
Current version is 1.4.0
Incremented version to 1.5.0
=> [Chore] Update readme and package.json 1.5.0

projects/go-lib/src/lib/components/go-icon-button/go-icon-button.component.scss
The current background color for `go-icon-button` does not look great against dark backgrounds.
Issue Number: #434 
The new hover background should look decent regardless of the surrounding background color.
=> Fix GoIconButton Hover Background

projects/go-lib/src/lib/components/go-select/go-select.component.html, projects/go-lib/src/lib/components/go-select/go-select.component.spec.ts, projects/go-lib/src/lib/components/go-select/go-select.component.ts, projects/go-lib/src/lib/components/go-select/go-select.module.ts
Issue Number: #439 
This adds a 'Select All' button to the `go-select` which enables one to select all available options.
=> Add Select All button to GoSelect

projects/go-style-guide/src/app/features/ui-kit/components/toast-docs/toast-docs.component.ts
We don't have an example of the toaster duration documented.
Issue Number: #296 
Added an example
=> [Chore] Document Toast Duration

projects/go-lib/src/lib/components/go-table/go-table.component.html, projects/go-lib/src/lib/components/go-table/go-table.component.scss
Currently, the table controls were custom styled buttons.
Issue Number: #301
Converted them to `go-icon-buttons`
=> [Convert] Table Controls to use icon-buttons

projects/go-lib/src/lib/components/go-button/go-button.component.scss
Buttons had a slightly shorter top/bottom padding
Closes #345 
Correct padding has been applied
=> [Chore] Update Button Padding

projects/go-lib/src/lib/components/go-modal/go-modal.component.scss
The modal is too short.
Issue Number: #426 
The modal can be taller
=> Chore update modal height

projects/go-lib/src/styles/_globals.scss, projects/go-lib/src/styles/styles.scss, projects/go-style-guide/src/styles/styles.scss
Scrollbars are determined by the browsers
Closes: #413 
For webkit browsers we now apply styles to all scrollbars
=> [Chore] Added styles for scrollbars globally

projects/go-lib/src/lib/components/go-header-bar/go-header-bar.component.scss, projects/go-lib/src/styles/_mixins.scss
The header bar's `box-shadow` property does not properly overlay on the page content below it in some cases.
Closes #415 
The header bar displays as it should.
=> [Bug] Header Bar box-shadow overlaps page content

projects/go-lib/src/lib/components/go-table/go-table-utils.spec.ts, projects/go-lib/src/lib/components/go-table/go-table-utils.ts
Issue Number: #450 
Tables with undefined values sort properly
=> Fix table sorting

projects/go-lib/src/lib/components/go-toast/go-toast.component.html, projects/go-lib/src/lib/components/go-toast/go-toast.component.scss, projects/go-lib/src/lib/components/go-toast/go-toast.component.spec.ts, projects/go-lib/src/lib/components/go-toast/go-toast.module.ts
The toast component was using older designs
Issue Number: #349 
Updated design per dsm spec. Additionally updated dismiss icon to use an `icon-button`.
=> [Chore] Update Toast Design

projects/go-lib/src/lib/components/go-table/go-table.component.html, projects/go-lib/src/lib/components/go-table/go-table.component.scss, projects/go-style-guide/src/app/features/ui-kit/components/table-docs/components/table-filters/table-filters.component.html, projects/go-style-guide/src/app/features/ui-kit/components/table-docs/components/table-filters/table-filters.component.ts, projects/go-style-guide/src/app/features/ui-kit/components/table-docs/table-docs.component.ts, projects/go-style-guide/src/app/features/ui-kit/routes/ui-kit-routing.module.ts, projects/go-style-guide/src/app/features/ui-kit/ui-kit.module.ts
There is no way to pass in filters into the table
Issue Number: #395 
There is now a content projection slot to allow implementors to project filters (`go-pill`s) into the table header.
=> [Feature] Table Filters

projects/go-lib/src/lib/components/go-modal/go-modal.service.spec.ts, projects/go-lib/src/lib/components/go-modal/go-modal.service.ts
We are missing unit tests for our GoModalService.
Issue Number: #389 
Tests have been added.
=> Add Unit Tests For GoModalService

projects/go-lib/src/lib/components/go-button/go-button.component.scss
Issue Number: https://github.com/mobi/goponents/issues/355
All buttons have the same height
=> All Buttons Same Height

projects/go-lib/src/lib/components/go-off-canvas/go-off-canvas.component.html
Updates Off Canvas header to match [DSM spec](https://tangoe.invisionapp.com/dsm/tangoe/tangoe-ds/folder/components/5d6ecba0bbf330b5e308562c)
=> Update off canvas header to match DSM spec

projects/go-lib/src/lib/components/go-icon-button/go-icon-button.component.scss, projects/go-lib/src/lib/components/go-icon/go-icon.component.scss, projects/go-style-guide/src/app/features/ui-kit/components/icon-button-docs/icon-button-docs.component.html
Issue Number: https://tangoe.invisionapp.com/dsm/tangoe/tangoe-ds/folder/icons/5c9435edae717d334e2b0c6a
Icon size and padding updated to match [DSM spec](https://tangoe.invisionapp.com/dsm/tangoe/tangoe-ds/folder/icons/5c9435edae717d334e2b0c6a)
=> Update icon sizes to match DSM spec

projects/go-lib/src/lib/components/go-datepicker/go-datepicker.component.scss, projects/go-lib/src/styles/_forms.scss, projects/go-lib/src/styles/_mixins.scss, projects/go-lib/src/styles/_variables.scss
Form controls did not quite have the correct design
Closes #361 
Updated the designs of the form controls to the DSM spec (minus the select)
=> [Chore] Form Control Design

README.md, projects/go-lib/package.json
Current version references `1.5.0`
Updated to reference `1.5.1`
=> [Chore] Updated README & package.json for 1.5.1

projects/go-lib/src/lib/components/go-select/go-select.component.scss, projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/form-control-docs/form-control-docs.component.ts, projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/select-docs/select-docs.component.ts
Select is not quite to the design standards of the DSM
Closes #407 
Closes #427 
Updated select to be consistent with that of the DSM
=> [Chore] Update Select Design

projects/go-lib/src/lib/components/go-table/go-table.component.scss, projects/go-lib/src/public_api.ts, projects/go-style-guide/src/app/features/ui-kit/components/table-docs/components/server-integration/server-integration.component.html, projects/go-style-guide/src/app/features/ui-kit/components/table-docs/components/table-overview/table-overview.component.ts, projects/go-style-guide/src/app/features/ui-kit/components/table-docs/components/table-searching/table-searching.component.html, projects/go-style-guide/src/app/features/ui-kit/components/table-docs/components/table-searching/table-searching.component.ts, projects/go-style-guide/src/app/shared/components/sub-nav/sub-nav.component.scss
- The `GoTableSearchConfig` class was not properly exported in the `public_api` class. Thus upon redistribution it was throwing an error when implementors tried to import the class.
- The documentation was not super clear on how to use the table search. 
- The Select input for page size formatting was off
- The box shadows on cards in a sub nav layout were cut off on the sides
Fixed all of the above issues to work as intended.
=> [Bug] Table Search Config

projects/go-lib/src/lib/components/go-select/go-select.component.scss
The select is misaligned
Closes #470 
Closes #452 
The select is aligned correctly
=> [Chore] Select Alignment Adjustments

projects/go-lib/src/lib/components/go-side-nav/go-side-nav/go-side-nav.component.scss, projects/go-style-guide/src/app/features/ui-kit/components/layout-docs/components/layout-app-drawer/layout-app-drawer.component.html, projects/go-style-guide/src/app/features/ui-kit/components/layout-docs/components/layout-nav/layout-nav.component.html, projects/go-style-guide/src/app/features/ui-kit/components/table-docs/components/table-searching/table-searching.component.html
Some `<a>` were missing the `go-link` class
Added those `go-link` classes.
=> [Chore] App Drawer Link Docs Fix

README.md, projects/go-lib/package.json
Showing old version
Updated to next version
=> [Chore] README & package.json to 1.5.2

README.md, projects/go-lib/package.json
=> Chore Readme Package Json

projects/go-lib/src/lib/components/go-off-canvas/go-off-canvas-service.spec.ts, projects/go-lib/src/lib/components/go-off-canvas/go-off-canvas.component.spec.ts, projects/go-lib/src/lib/components/go-off-canvas/go-off-canvas.service.ts
Issue Number: #386 
Added unit tests for go-off-canvas component and service.
=> Add go-off-canvas unit tests

projects/go-lib/src/lib/components/go-side-nav/go-side-nav/go-side-nav.component.scss
Padding was being applied to the wrong element in the side nav causing a weird overflow issue
Closes #481 
Behaves as intended
=> [Bug] Padding Sidenav

projects/go-lib/src/lib/components/go-footer/go-footer.component.scss, projects/go-lib/src/lib/components/go-layout/go-layout.component.html, projects/go-lib/src/lib/components/go-layout/go-layout.component.scss
Update footer to match DSM https://tangoe.invisionapp.com/dsm/tangoe/tangoe-ds/folder/components/5d4dd6199dada53893b6a783
=> update footer styles to match DSM

projects/go-lib/src/lib/components/go-table/go-table-search-config.model.ts, projects/go-lib/src/lib/components/go-table/go-table.component.html, projects/go-lib/src/lib/components/go-table/go-table.component.scss, projects/go-lib/src/lib/components/go-table/go-table.component.spec.ts, projects/go-lib/src/lib/components/go-table/go-table.component.ts, projects/go-style-guide/src/app/features/ui-kit/components/table-docs/components/table-overview/table-overview.component.html, projects/go-style-guide/src/app/features/ui-kit/components/table-docs/components/table-overview/table-overview.component.ts, projects/go-style-guide/src/app/features/ui-kit/components/table-docs/components/table-searching/table-searching.component.html, projects/go-style-guide/src/app/features/ui-kit/components/table-docs/components/table-searching/table-searching.component.ts
- The search term of the table search cannot be set on init
- The placeholder or debounce time of the table search cannot be changed. 
- The max height of the table cannot be specified
- The table search cannot be easily cleared
Closes #479, #482, #480 
- Allows the search term of the table to be set on init
- Adds the ability to change the placeholder or debounce time of the table search
- Adds the ability to specify a max height on the table content
- Adds a clear icon to the table search to easily clear the search term
=> [Chore] Table Search Updates

projects/go-lib/src/lib/components/go-header-bar/go-header-bar.component.ts
~Docs have been added / updated (for bug fixes / features)~
Currently there is an error when running tests that we are trying to unsubscribe from a subscription that doesn't exist.
We check if there is a subscription before we try to unsubscribe.
=> Test Errors

README.md, projects/go-lib/package.json
The README and package.json show the current version number.
Updated to reflect the next version number
=> [Chore] Upgrade README & package.json to v1.5.3

projects/go-lib/src/lib/components/go-radio/go-radio-button.component.html, projects/go-lib/src/lib/components/go-radio/go-radio-button.component.ts, projects/go-lib/src/lib/components/go-radio/go-radio-group.component.spec.ts, projects/go-lib/src/lib/components/go-radio/go-radio-group.component.ts, projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/radio-button-docs/radio-button-docs.component.ts
Issue Number: https://github.com/mobi/goponents/issues/488
When using an *ngFor with radio buttons there is no error in the console
=> Radio Button Loop Bug

projects/go-lib/src/lib/components/go-action-sheet/go-action-sheet.component.scss, projects/go-lib/src/lib/components/go-action-sheet/go-action-sheet.component.ts, projects/go-style-guide/src/app/app.component.html, projects/go-style-guide/src/app/app.module.ts, projects/go-style-guide/src/app/features/ui-kit/components/action-sheet-docs/components/action-sheet-overview/action-sheet-overview.component.html, projects/go-style-guide/src/app/features/ui-kit/components/action-sheet-docs/components/action-sheet-overview/action-sheet-overview.component.ts
Currently the `shiftLeft` binding on the `go-action-sheet` component does not position the action sheet content appropriately.
Closes #494 
Makes the `shiftLeft` binding work as intended
=> [Bug] Fix Action-sheet shiftLeft binding

projects/go-lib/src/lib/components/go-layout/go-layout.component.html, projects/go-style-guide/src/app/features/ui-kit/components/layout-docs/components/layout-overview/layout-overview.component.html, projects/go-style-guide/src/app/features/ui-kit/components/layout-docs/components/layout-overview/layout-overview.component.ts
~Tests for the changes have been added (for bug fixes / features)~
Currently if we want to add content to the top of every page, the content has to be actually added to every page. This becomes burdensome to make sure it's added to every page. 
This allows the ability to drop content onto the top of every page above the router outlet.
=> Content Projection at the top of the Layout

projects/go-lib/src/lib/components/go-header/go-header.component.ts
Issue Number: https://github.com/mobi/goponents/issues/501
There is no error when running the project with Angular 9
=> Middle Content Exists Error

README.md, projects/go-lib/package.json
Targets current latest version
Updates README and package.json to reflect new version
=> [Chore] Update README & package.json for version 1.5.4

projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/select-docs/select-docs.component.html, projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/select-docs/select-docs.component.ts
There was a typo and a duplicated control in the select docs.
Fixed those
=> [Chore] Fix select docs typo

projects/go-lib/src/lib/components/go-copy/go-copy.component.html
~Tests for the changes have been added (for bug fixes / features)~
~Docs have been added / updated (for bug fixes / features)~
Issue Number: https://github.com/mobi/goponents/issues/517
Tabing through a page with a copy button skips over the text area associated with the copy button.
=> Copy Button Tabable

projects/go-lib/src/lib/components/go-side-nav/custom-nav-attribute.model.ts, projects/go-lib/src/lib/components/go-side-nav/go-nav-group/go-nav-group.component.html, projects/go-lib/src/lib/components/go-side-nav/go-nav-group/go-nav-group.component.ts, projects/go-lib/src/lib/components/go-side-nav/go-nav-item/go-nav-item.component.html, projects/go-lib/src/lib/components/go-side-nav/go-nav-item/go-nav-item.component.ts, projects/go-lib/src/lib/components/go-side-nav/go-side-nav/go-side-nav.service.spec.ts, projects/go-lib/src/lib/components/go-side-nav/go-side-nav/go-side-nav.service.ts, projects/go-lib/src/lib/components/go-side-nav/nav-group.model.ts, projects/go-lib/src/lib/components/go-side-nav/nav-item.model.ts, projects/go-style-guide/src/app/features/ui-kit/components/layout-docs/components/layout-nav/layout-nav.component.html, projects/go-style-guide/src/app/features/ui-kit/components/layout-docs/components/layout-nav/layout-nav.component.ts
Issue Number: #515 
Added the ability to add custom attributes to each menu item of the go-side-nav.
=> Add ability to add custom attributes to go-side-nav menu items

projects/go-lib/src/lib/components/go-accordion/go-accordion-panel.component.scss
Issue Number: #516 
It works as expected
=> [Bug] Slim & noConentPadding Accordion Issue

projects/go-lib/src/lib/components/go-table/go-table.component.scss
The sort icon on table headers is slightly mis-aligned with the header text.
Issue Number: #530 
Correctly aligned.
=> [Bug] Table Sort Icon Alignment

projects/go-lib/src/lib/components/go-header/go-header.component.html, projects/go-lib/src/lib/components/go-header/go-header.component.ts, projects/go-lib/src/lib/components/go-header/go-header.module.ts, projects/go-style-guide/src/app/features/ui-kit/components/layout-docs/components/layout-header/layout-header.component.html, projects/go-style-guide/src/app/features/ui-kit/components/layout-docs/components/layout-header/layout-header.component.ts
The logo area does not have the ability to be a link.
Issue Number: #518 
Provides the ability to pass either an href or routerLink for the logo area.
=> [Chore] Add Link to Logo Area in Header

projects/go-lib/src/lib/components/go-select/go-select.component.scss
There is no transition on the hover/active effects
Adds the same transition that regular inputs have
=> [Chore] Add transition Property to go-select

README.md, projects/go-lib/package.json
Current referenced version is v1.5.4
Updated to next patch v1.5.5
=> [Chore] Update README and package.json for v1.5.5

projects/go-lib/src/lib/components/go-copy/go-copy.component.html, projects/go-lib/src/lib/components/go-copy/go-copy.component.scss, projects/go-lib/src/lib/components/go-copy/go-copy.component.ts
Inside of a table cell, the current overflow implementation does not work.
Implemented absolute positioning on the host element to ensure proper overflow.
=> [Bug] Copy Button Overflow

projects/go-lib/src/lib/components/go-table/go-table-utils.spec.ts, projects/go-lib/src/lib/components/go-table/go-table-utils.ts
If a row in the table contains a value that is either undefined or null, searching on the table will throw a type error.
If a field is null or undefined, convert it to an empty string when extracting it for use.
TDD is cool sometimes.
=> Fix table search with null or undefined

projects/go-lib/src/lib/components/go-off-canvas/go-off-canvas.component.scss, projects/go-lib/src/lib/components/go-side-nav/go-side-nav/go-side-nav.component.scss, projects/go-lib/src/styles/_forms.scss, projects/go-lib/src/styles/_variables.scss
Issue Number: #414 
Our dark theme colors have been updated to conform with the Tangoe DSM.
=> Update dark theme colors

projects/go-lib/src/lib/components/go-header/go-header.component.html, projects/go-lib/src/lib/components/go-header/go-header.component.ts, projects/go-lib/src/lib/components/go-search/go-search.component.html, projects/go-lib/src/lib/components/go-search/go-search.component.scss, projects/go-lib/src/lib/components/go-search/go-search.component.spec.ts, projects/go-lib/src/lib/components/go-search/go-search.component.ts, projects/go-lib/src/lib/components/go-search/go-search.service.ts, projects/go-lib/src/styles/_typography.scss, projects/go-style-guide/src/app/features/ui-kit/components/layout-docs/components/layout-search/layout-search.component.html
The search bar in the middle section of the header that threw an error in a compiled application.
Fixed this issue, as well as implemented a few other adjustments and updates to the search.
=> [Chore] Search Updates

projects/go-lib/src/lib/components/go-toast/go-toast.component.html, projects/go-lib/src/lib/components/go-toast/go-toast.component.scss, projects/go-lib/src/lib/components/go-toast/go-toast.component.ts, projects/go-style-guide/src/app/features/ui-kit/components/toast-docs/toast-docs.component.html, projects/go-style-guide/src/app/features/ui-kit/components/toast-docs/toast-docs.component.ts, projects/go-tester/src/app/components/test-page-2/test-page-2.component.html, projects/go-tester/src/app/components/test-page-2/test-page-2.component.ts
Issue Number: #550 
Added the button ability inside of the toast.
=> [Feature] Added button inside of Toast

.gitignore, README.md, projects/go-lib/package.json, projects/go-lib/src/lib/components/go-search/go-search.component.ts, projects/go-style-guide/src/app/features/ui-kit/components/toast-docs/toast-docs.component.html
Old version number
Increased the version number to v1.5.6
Minor formatting fixes for v1.5.6
=> [Chore] Minor Fixes for v1.5.6 and version bump

projects/go-lib/src/lib/components/go-table/go-table-column.component.ts, projects/go-lib/src/lib/components/go-table/go-table.component.html, projects/go-style-guide/src/app/features/ui-kit/components/table-docs/components/table-column-docs/table-column-docs.component.html, projects/go-style-guide/src/app/features/ui-kit/components/table-docs/components/table-column-docs/table-column-docs.component.ts
Issue Number: #556 
Added ability to specific a vertical alignment to each table column with a default of `middle`.
=> [Chore] Added Alignment to Table Column

projects/go-lib/src/styles/_typography.scss
Issue Number: #557 
Adds a `font-weight` property to the `<strong>` element
=> [Chore] Added Styles for Strong elements

projects/go-lib/src/lib/components/go-header-bar/go-header-bar.component.scss
Issue Number: #539 
Changed header bar arrow styles to match those in dsm
=> [Chore] Update Header Bar Styles

projects/go-lib/src/public_api.ts
The `GoHeaderBarService` is not exposed in the `public_api`
Issue Number: Part of #570 
The `GoHeaderBarService` is now properly exposed in the `public_api`
=> [Chore] Expose GoHeaderBarService

projects/go-lib/src/lib/components/go-side-nav/go-side-nav/go-side-nav.component.scss, projects/go-lib/src/lib/components/go-side-nav/go-side-nav/go-side-nav.component.ts
Issue Number: #560 
Applied appropriate padding to first link
=> [Chore] Updated Styles for First Link in Side Nav

CONTRIBUTING.md, README.md, projects/go-lib/package.json
Pointed at current version `v1.5.6`
Updated to new patch version `v1.5.7`
=> [Chore] Updates README & package.json to v1.5.7

projects/go-lib/src/lib/components/go-side-nav/go-nav-group/go-nav-group.component.html, projects/go-lib/src/lib/components/go-side-nav/go-nav-group/go-nav-group.component.ts, projects/go-lib/src/lib/components/go-side-nav/go-side-nav/go-side-nav.component.html, projects/go-lib/src/lib/components/go-side-nav/go-side-nav/go-side-nav.component.scss
Some items in the side nav had incorrect spacing/padding depending on certain circumstances.
Fixed those in accordance with dsm
=> [Bug] Sidenav Active Item Spacing

projects/go-lib/src/lib/components/go-header-bar/go-header-bar.directive.spec.ts, projects/go-lib/src/lib/components/go-header-bar/go-header-bar.directive.ts
The `GoHeaderBarDirective` does not update the `GoHeaderBarComponent` when it receives changes.
Issue Number: #570 
The `GoHeaderBarDirective` registers changes and sends updates to the `GoHeaderBarComponent` accordingly.
=> Bug Header Bar OnChanges

README.md, projects/go-lib/package.json
README and package.json show `v1.5.7`
README and package.json show `v1.5.8`
=> [Chore] Update README and package.json for v1.5.8

projects/go-lib/src/lib/components/go-header-bar/go-header-bar.component.html, projects/go-lib/src/lib/components/go-header-bar/go-header-bar.component.scss, projects/go-lib/src/lib/components/go-header-bar/go-header-bar.component.ts, projects/go-lib/src/lib/components/go-layout/go-layout.component.html, projects/go-lib/src/lib/components/go-layout/go-layout.component.scss
When switching between routes that have different header bar's, the previous header bar's content would still persist and causing a "jumping" of the new header bar's content.
Issue Number: #524 
This no longer happens.
=> [Bug] Header Bar Actions Shifting

README.md, projects/go-lib/package.json
Library points to `v1.5.8`
Library now points to `v1.5.9`
=> Updates app for v1.5.9

package-lock.json, package.json, projects/go-lib/package.json
Current `ng-select` version is not compatible with Angular v8
Upgraded to `ng-select` version that is compatible with Angular v8
This _should_ not be a breaking change because `ng-select` is a peer dependency of Goponents which means the version installed is controlled by the installing application.
=> [Chore] ng-select upgrade for Angular v8 compatability

.github/PULL_REQUEST_TEMPLATE.md
=> [Chore] Update and Simplify PR Template

projects/go-lib/src/lib/components/go-button/go-button.component.scss, projects/go-lib/src/lib/components/go-select/go-select.component.scss, projects/go-lib/src/styles/_forms.scss, projects/go-lib/src/styles/_mixins.scss, projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/select-docs/select-docs.component.ts
The selects, buttons, and form inputs were inconsistent in heights
Issue Number: #591 
Aligned heights, font size, and line height for selects, buttons, and form inputs to match specifications in dsm
=> [Bug] Align Form Heights

projects/go-lib/src/lib/components/go-table/go-table.component.html, projects/go-lib/src/lib/components/go-table/go-table.component.scss, projects/go-lib/src/lib/components/go-table/go-table.component.ts, projects/go-style-guide/src/app/features/ui-kit/components/table-docs/components/table-title-template/table-title-template.component.html, projects/go-style-guide/src/app/features/ui-kit/components/table-docs/components/table-title-template/table-title-template.component.ts, projects/go-style-guide/src/app/features/ui-kit/components/table-docs/table-docs.component.ts, projects/go-style-guide/src/app/features/ui-kit/routes/ui-kit-routing.module.ts, projects/go-style-guide/src/app/features/ui-kit/ui-kit.module.ts
The table title can only be a string passed in as a binding through the table.
Resolves #519 
An `ng-template` can now be declared in place of the `tableTitle` area.
=> [Feature] Table Title Template

projects/go-lib/src/styles/_variables.scss, projects/go-style-guide/src/app/features/standards/components/colors/colors.component.html, projects/go-style-guide/src/app/features/standards/components/colors/colors.component.ts
Resolves #603 
Corrected colors
=> [Chore] Update Horizon and Nebula hex

projects/go-lib/src/lib/components/go-select/go-select.component.html, projects/go-lib/src/lib/components/go-select/go-select.component.scss, projects/go-lib/src/styles/_variables.scss
Resolves #575 
Fixed styles per instructions in PR
=> [Chore] Select Options Styles Update

projects/go-lib/src/lib/components/go-select/go-select.component.scss
When applying a `title` on a label template it was not appearing because the element that the template get's rendered was "under" the input element because of `z-index` and `position`.
Adding a `z-index` to the element to push it above the input.
=> [Bug] Label Title Hover Select

projects/go-lib/src/lib/components/go-side-nav/go-nav-group/go-nav-group.component.scss, projects/go-lib/src/lib/components/go-side-nav/go-nav-item/go-nav-item.component.scss, projects/go-lib/src/lib/components/go-side-nav/go-side-nav/go-side-nav.component.scss, projects/go-lib/src/styles/_variables.scss, projects/go-style-guide/src/styles/_settings.scss, projects/go-tester/src/styles.scss
Resolves #584 
* Side-nav icon sizes set to 1rem.
* App Drawer icon size set to 1.5rem.
* Active side nav item font-weights set to 600.
* Nunito font-weight imports updated to include only 300 and 600.
=> Side Nav Style Updates

projects/go-lib/src/lib/components/go-select/go-select.component.html, projects/go-lib/src/lib/components/go-select/go-select.component.ts, projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/select-docs/select-docs.component.html, projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/select-docs/select-docs.component.ts
Cannot change "Type to search" text on `ng-select` typeahead
Exposed `ng-select` binding to change the text
=> [Feature] Select Typeahead Search Text

projects/go-lib/src/lib/components/go-accordion/go-accordion-panel.component.scss, projects/go-lib/src/lib/components/go-button/go-button.component.scss, projects/go-lib/src/lib/components/go-select/go-select.component.scss, projects/go-lib/src/styles/_variables.scss, projects/go-style-guide/src/app/features/standards/components/colors/colors.component.ts
The light and dark `bg` color variables for `active` and `hover` are switched in their names and values.
This corrects the variable declarations.
`
=> [Chore] Correct Light Bg Color Variables

projects/go-lib/src/lib/components/go-header/go-header.component.spec.ts
Resolves #388
This adds unit tests for the header component.
=> Add header component unit tests

projects/go-style-guide/src/app/app.component.ts, projects/go-style-guide/src/app/features/ui-kit/components/virtual-scroll/virtual-scroll.component.html, projects/go-style-guide/src/app/features/ui-kit/components/virtual-scroll/virtual-scroll.component.ts, projects/go-style-guide/src/app/features/ui-kit/routes/ui-kit-routing.module.ts, projects/go-style-guide/src/app/features/ui-kit/ui-kit.module.ts
We don't have any sort of specification or feature for virtual/infinite scroll.
Documents our decision to adopt Material's CDK for virtual/infinite scroll.
=> [Chore] Virtual Scroll Docs

projects/go-lib/src/lib/components/go-copy/go-copy.component.spec.ts
Typo in a test for `go-copy`
Corrected typo
=> [Chore] go-copy Test Typo

README.md, projects/go-lib/package.json
Docs target `v1.5.9` of Goponents
Changed to target `v1.6.0` and changes for that version
=> [Chore] v1.6.0 Docs Update

projects/go-lib/src/styles/_grid.scss
N/A
Adds utility class to allow a column to expand past its width.
Example:
```
<div class="go-column go-column--33">
</div>
<div class="go-column go-column--33 go-column--expandable">
</div>
```
=> [Feature] Expandable Grid Column

projects/go-lib/src/lib/components/go-button/go-button.component.scss
Button `line-height` is `1.3`
Corrected button `line-height` to `1.2`
=> [Bug] Button Line Height

projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/select-docs/select-docs.component.ts
formControl name in one of the examples is wrong.
Resolves : no issue created for this.
formControl name corrected for the example, under 'Component Errors' section.
=> Update an example for goSelect

projects/go-lib/src/lib/components/go-table/go-table.component.scss, projects/go-lib/src/styles/_variables.scss, projects/go-style-guide/src/app/features/ui-kit/components/table-docs/components/table-actions-docs/table-actions-docs.component.html, projects/go-style-guide/src/app/features/ui-kit/components/table-docs/components/table-actions-docs/table-actions-docs.component.ts, projects/go-tester/src/app/components/test-page-1/test-page-1.component.html
Resolves [605](https://github.com/mobi/goponents/issues/605)
Styling changes for table action icons, table column header and table search input.
=> Update table design

README.md, projects/go-lib/package.json
Targeting v1.6.0
Targets v1.6.1
=> [Chore] v1.6.1 Documentation Update

projects/go-lib/src/lib/components/go-off-canvas/go-off-canvas.component.scss
=> Add flex wrap to large off canvas header

projects/go-style-guide/src/app/features/ui-kit/components/action-sheet-docs/components/action-sheet-overview/action-sheet-overview.component.html, projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/checkbox-docs/checkbox-docs.component.html, projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/radio-button-docs/radio-button-docs.component.html
This PR fixes a typo in form-docs and action-sheet-docs.
=> Fixed a typo in form-docs and action-sheet-docs

projects/go-lib/src/lib/components/go-side-nav/go-side-nav/go-side-nav.component.html, projects/go-lib/src/lib/components/go-side-nav/go-side-nav/go-side-nav.component.scss
Resolves #651 
The styles of the "Switch to..." panel of the app-drawer action-sheet now match the specifications of the DSM.
=> Update header panel of app drawer styles to match DSM

projects/go-lib/src/lib/components/go-badge/go-badge.component.html, projects/go-lib/src/lib/components/go-badge/go-badge.component.scss, projects/go-lib/src/lib/components/go-badge/go-badge.component.ts
Resolves #658 
This makes it so that the `go-badge` will be positioned correctly when used with a `go-icon-button`.
=> Fix go-badge position on go-icon-buttons

projects/go-lib/src/styles/_typography.scss
We don't define a base color for text.
Because the default "theme" is the "light" theme, I am defining the body's `color` property to the `theme-light-color` variable.
=> [Chore] Base Color

projects/go-lib/src/lib/components/go-checkbox/go-checkbox.component.html, projects/go-lib/src/lib/components/go-checkbox/go-checkbox.component.spec.ts, projects/go-lib/src/lib/components/go-checkbox/go-checkbox.component.ts, projects/go-lib/src/lib/components/go-table/go-table.component.html, projects/go-lib/src/lib/components/go-table/go-table.component.scss, projects/go-lib/src/lib/components/go-table/go-table.component.spec.ts, projects/go-lib/src/lib/components/go-table/go-table.component.ts, projects/go-lib/src/lib/components/go-table/go-table.module.ts, projects/go-lib/src/lib/directives/go-copy-card-link/go-copy-card-link.directive.spec.ts, projects/go-lib/src/styles/_forms.scss, projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/checkbox-docs/checkbox-docs.component.html, projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/checkbox-docs/checkbox-docs.component.ts, projects/go-style-guide/src/app/features/ui-kit/components/table-docs/components/table-selection/table-selection.component.html
Resolves #656 
This PR updates the background color of the `go-checkbox` to match the DSM and also integrates the `go-checkbox` into the `go-table`.
=> Update go-checkbox background color and integrate into go-table

projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/select-docs/select-docs.component.html, projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/select-docs/select-docs.component.ts
Details here #694 
Resolves #694 
Docs for go-select have been updated.
=> Updated docs for go-select disable mode

projects/go-lib/src/lib/components/go-table/go-table.component.html, projects/go-lib/src/lib/components/go-table/go-table.component.ts, projects/go-style-guide/src/app/features/ui-kit/components/table-docs/components/table-overview/table-overview.component.html, projects/go-style-guide/src/app/features/ui-kit/components/table-docs/components/table-overview/table-overview.component.ts
No `min-height` support in `go-table`
Resolves https://github.com/mobi/goponents/issues/702
`min-height` support added to `go-table`
=> Add support for min-height to go-table

projects/go-lib/src/lib/components/go-hint/go-hint.component.scss, projects/go-lib/src/lib/components/go-search/go-search.component.scss, projects/go-lib/src/styles/_mixins.scss
At several places in the UI, colors were not up to date as per the latest style guide.
Resolves [323](https://github.com/mobi/goponents/issues/323)
Neutral colors have been updated as per details mentioned in issue description and comments.
=> Update Neutral Colors as per DSM (Issue #323)

projects/go-lib/src/lib/components/go-accordion/go-accordion-panel.component.ts, projects/go-lib/src/lib/components/go-accordion/go-accordion.component.ts, projects/go-lib/src/lib/components/go-file-upload/go-file-upload.component.ts, projects/go-lib/src/lib/components/go-layout/go-layout.component.ts, projects/go-lib/src/lib/components/go-modal/go-modal.component.ts, projects/go-lib/src/lib/components/go-off-canvas/go-off-canvas.component.ts, projects/go-lib/src/lib/components/go-search/go-search.component.ts, projects/go-lib/src/lib/components/go-side-nav/go-nav-group/go-nav-group.component.ts, projects/go-lib/src/lib/components/go-side-nav/go-nav-item/go-nav-item.component.ts, projects/go-lib/src/lib/components/go-side-nav/go-side-nav/go-side-nav.component.ts, projects/go-lib/src/lib/components/go-table/go-table.component.ts, projects/go-style-guide/src/app/features/ui-kit/components/configuration-docs/configuration-docs.component.ts, projects/go-style-guide/src/app/features/ui-kit/components/header-bar-docs/header-bar-docs.component.ts, projects/go-tester/src/app/components/search-test/search-test.component.ts, projects/go-tester/src/app/components/test-page-1/test-page-1.component.ts
Resolves #689 
This ensures that we are unsubscribing from all of the non-http subscriptions within our components in order to prevent potential memory leaks.
=> Unsubscribe in components to prevent memory leaks

projects/go-lib/src/lib/components/go-accordion/go-accordion.component.spec.ts, projects/go-lib/src/lib/components/go-accordion/go-accordion.component.ts
Resolves #669 
Dynamically created accordions function the same as html driven accordions
=> Dynamically Created Accordions Not Opening

README.md, projects/go-lib/package.json
Targeting `v.1.6.1`
Targets `v1.7.0`
=> [Chore] Update Docs for v1.7.0

projects/go-lib/src/lib/components/go-button/go-button.component.scss
Regular buttons are not quite the right height
Adjust buttons to be consistent heights for regular, icon only, and split buttons.
=> [Bug] Button Height

projects/go-lib/src/lib/components/go-radio/go-radio-group.component.html, projects/go-lib/src/lib/components/go-side-nav/go-side-nav/go-side-nav.component.scss, projects/go-lib/src/styles/_forms.scss
See, https://github.com/mobi/goponents/pull/711#pullrequestreview-529217516
Address items outlined in #711
=> [Chore] 1.7.0 review cleanup

projects/go-lib/src/lib/components/go-hint/go-hint.component.scss, projects/go-lib/src/styles/_hints.scss, projects/go-lib/src/styles/_mixins.scss, projects/go-lib/src/styles/_typography.scss, projects/go-lib/src/styles/_variables.scss
Letter spacing for text elements that use font Roboto 300, were not as per design guidelines.
Resolves #710 
Letter spacing for such text elements has been updated to 0.08pt.
=> Fix Letter Spacing

projects/go-lib/src/lib/animations/route.animation.ts, projects/go-lib/src/lib/components/go-layout/go-layout.component.html, projects/go-lib/src/lib/components/go-layout/go-layout.component.scss, projects/go-tester/src/app/components/layout/layout.component.ts
The animations between routes sometimes cause the content to snap up the page. 
It no longer does this.
=> [Bug] go-layout Route Animation Snapping

projects/go-lib/src/lib/components/go-accordion/go-accordion-panel.component.scss
Accordion header font weights were `light` instead of `regular`
Updates font weight on Accordion headers to be in line with DSM. Also updates formatting of scss file to match correct BEM syntax.
=> [Chore] Accordion Font Weight

README.md, projects/go-lib/package.json
References version `1.7.0`
References version `1.7.1`
=> [Chore] v1.7.1 Documentation Update

README.md, projects/go-lib/package.json
Build is targeted at `v1.7.1`
Build is targeted at `v1.8.0`
=> [Chore] v1.8.0 Documentation Update

projects/go-lib/src/lib/components/go-header/go-header.component.scss, projects/go-lib/src/styles/_variables.scss
Resolves #729 
Left nav is now 250px wide
=> [Bug] Side Nav Width

projects/go-lib/src/lib/components/go-timepicker/go-timepicker.component.ts, projects/go-lib/src/lib/components/go-timepicker/go-timepicker.component.ts.spec.ts
After change value, Updated value will display.
Resolves [738](https://github.com/mobi/goponents/issues/738)
After change value, Updated value will display.
=> resolve value changes issue

projects/go-lib/src/lib/go-shared.module.ts
Resolves #718
Imports and exports all modules
=> [Chore] Update Shared Module

projects/go-style-guide/src/app/app.component.ts, projects/go-style-guide/src/app/features/ui-kit/components/wysiwyg-docs/wysiwyg-docs.component.html, projects/go-style-guide/src/app/features/ui-kit/components/wysiwyg-docs/wysiwyg-docs.component.ts, projects/go-style-guide/src/app/features/ui-kit/routes/ui-kit-routing.module.ts, projects/go-style-guide/src/app/features/ui-kit/ui-kit.module.ts
Resolves #727 
Documents our usage of a WYSIWYG editor.
=> [Chore] WYSIWYG Documentation

projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/timepicker-docs/timepicker-docs.component.ts
Update **go-timepicker** text instead of **go-datepicker**.
=> Resolve document issues of go-timepicker module.

projects/go-lib/src/lib/components/go-table/go-table.component.scss
Resolves #709 
A 2px border appears beneath the table headers and above the table toolbar.
=> [Chore] Table Content Borders

projects/go-lib/src/lib/components/go-table/go-table-utils.spec.ts, projects/go-lib/src/lib/components/go-table/go-table-utils.ts, projects/go-style-guide/src/app/features/ui-kit/components/table-docs/components/table-column-docs/table-column-docs.component.html, projects/go-style-guide/src/app/features/ui-kit/components/table-docs/components/table-column-docs/table-column-docs.component.ts, projects/go-style-guide/src/app/features/ui-kit/components/table-docs/table-docs.service.ts, projects/go-style-guide/src/app/features/ui-kit/ui-kit.module.ts
If a table column value was a `false` boolean it would be returned and displayed as `''`.
Resolves #681 
If table column is of type `boolean`, it returns the value as the string version of a boolean.
=> [Bug] Table False Values

projects/go-lib/src/styles/_forms.scss, projects/go-lib/src/styles/_grid.scss, projects/go-style-guide/src/app/features/standards/components/forms/forms.component.html, projects/go-style-guide/src/app/features/standards/components/forms/forms.component.ts, projects/go-style-guide/src/app/features/standards/components/grid/grid.component.html, projects/go-style-guide/src/app/features/standards/components/grid/grid.component.ts, projects/go-style-guide/src/app/features/standards/standards.module.ts, projects/go-style-guide/src/app/features/ui-kit/components/basic-test-large/basic-test-large.component.html, projects/go-style-guide/src/app/features/ui-kit/components/basic-test/basic-test.component.html, projects/go-style-guide/src/styles/styles.scss
Forms use the normal grid.
Resolves #455 
Adds a new modifier class to the grid to be used for forms.
Documentation for this can be found in the style guide at `/standards/grid/#form-container`.
=> [Feature] Forms Grid

projects/go-lib/src/lib/components/go-toaster/go-toaster.component.html, projects/go-lib/src/lib/components/go-toaster/go-toaster.component.scss
The first item in the toaster cuts off the box shadow above it.
Resolves #756 
Doesn't do that.
=> [Bug] Toaster Top

projects/go-lib/src/lib/components/go-button-group/go-button-group.component.html, projects/go-lib/src/lib/components/go-button-group/go-button-group.component.spec.ts, projects/go-lib/src/lib/components/go-button-group/go-button-group.component.ts, projects/go-lib/src/lib/components/go-button-group/go-button-group.module.ts, projects/go-lib/src/lib/components/go-button/go-button.component.scss, projects/go-lib/src/lib/components/go-button/go-button.component.spec.ts, projects/go-lib/src/lib/components/go-button/go-button.component.ts, projects/go-lib/src/lib/go-shared.module.ts, projects/go-lib/src/public_api.ts, projects/go-style-guide/src/app/app.component.ts, projects/go-style-guide/src/app/features/ui-kit/components/button-group-docs/button-group-docs.component.html, projects/go-style-guide/src/app/features/ui-kit/components/button-group-docs/button-group-docs.component.ts, projects/go-style-guide/src/app/features/ui-kit/routes/ui-kit-routing.module.ts, projects/go-style-guide/src/app/features/ui-kit/ui-kit.module.ts
Buttons cannot be grouped in the manner UX is specifying
Resolves #688 
A new component that allows you to specify a group of buttons that share variants and disabled states.
=> [Feature] Button Groups

README.md, projects/go-lib/package.json
Currently targeting `v1.8.0`
Updated to target `v1.9.0`
=> [Chore] v1.9.0 Documentation Update

README.md, projects/go-lib/package.json
=> [Chore] v1.9.1 Documentation Update

projects/go-lib/src/lib/components/go-toast/go-toast.component.html, projects/go-lib/src/lib/components/go-toast/go-toast.component.scss, projects/go-lib/src/lib/components/go-toast/go-toast.component.ts, projects/go-style-guide/src/app/features/ui-kit/components/toast-docs/toast-docs.component.html, projects/go-style-guide/src/app/features/ui-kit/components/toast-docs/toast-docs.component.ts
**go-toast**  has no ux features for dark theme
Resolves [737](https://github.com/mobi/goponents/issues/737)
The ability to style a **go-toast** for a dark theme.
=> Integrate toast functionality for dark theme

projects/go-lib/src/lib/components/go-datepicker/go-datepicker.component.spec.ts, projects/go-lib/src/lib/components/go-datepicker/go-datepicker.component.ts, projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/datepicker-docs/datepicker-docs.component.html, projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/datepicker-docs/datepicker-docs.component.ts
We are not able to reset the form such date picker control.
Resolves : GSCMD-736
We are able reset the form such date picker control. Because we have implemented new reset functionality.
=> [Bug] Datepicker Not Resetting Correctly

README.md, projects/go-lib/package.json
~~Tests for the changes have been added
Currently pointing to `v1.9.1`
Updates the library to point to `v1.10.0`
=> Chore Documentaiton Upgrade v1.10.0

projects/go-lib/src/lib/components/go-toaster/go-toaster.component.html, projects/go-lib/src/lib/components/go-toaster/go-toaster.component.ts, projects/go-lib/src/lib/components/go-toaster/go-toaster.service.spec.ts, projects/go-lib/src/lib/components/go-toaster/go-toaster.service.ts, projects/go-style-guide/src/app/features/ui-kit/components/toast-docs/toast-docs.component.ts
This commit fixes a bug where the 'dismissable' argument in the go-toaster service
isn't actually allowing toasts to be dismissable.
=> Bugfix: Dismissable Argument in Go-Toaster Service

projects/go-lib/src/styles/_forms.scss
Resolves #796 
Fieldsets should no longer be transformed to uppercase.
=> [Chore] Remove Fieldset Uppercase

projects/go-lib/src/lib/components/go-toast/go-toast.component.scss
Toast message body was a lil squished
Added some line height to space the content better vertically.
=> [Chore] Toast Message Formatting

projects/go-lib/src/lib/components/go-header-bar/go-header-bar.component.scss
Resolves #785
Correct padding on right side of header bar
=> [Chore] Header Bar Right Padding

projects/go-lib/src/lib/components/go-required-text/go-required-text.component.scss, projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/forms-overview/forms-overview.component.html, projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/forms-overview/forms-overview.component.ts
Resolves #787
- Added documentation around required form inputs
- Increased size of required asterisk to 14px
=> [Chore] Fix Size and Document Required Asterisk

projects/go-lib/src/lib/components/go-side-nav/go-nav-group/go-nav-group.component.html, projects/go-lib/src/lib/components/go-side-nav/go-nav-group/go-nav-group.component.scss, projects/go-lib/src/lib/components/go-side-nav/go-side-nav/go-side-nav.component.html, projects/go-lib/src/lib/components/go-side-nav/go-side-nav/go-side-nav.component.scss, projects/go-tester/src/app/components/layout/layout.component.ts
Resolves #794
Icon sizes for right side of side nav are now consistently 20px.
=> [Chore] Side Nav Right Icon Sizes

projects/go-lib/src/lib/components/go-table/go-table.component.scss
If table numbers got to triple digits the circle becomes an oval.
If table numbers get into triple digits the circle becomes a rounded rectangle.
=> [Chore] Table Page Numbers Border Radius

README.md, projects/go-lib/package.json
Pointed at `v1.10.0`
Points to new version of `v1.11.0`
=> [Chore] v1.11.0 Docs Update

projects/go-lib/src/lib/components/go-button/go-button.component.scss
Resolves #798 
Updates secondary button to look as specified.
=> [Chore] go-button Secondary Colors

projects/go-lib/src/lib/components/go-radio/go-radio-button.component.scss, projects/go-lib/src/lib/components/go-switch-toggle/go-switch-toggle.component.scss, projects/go-lib/styles/_forms.scss
Resolves #770 
Matches design provided by UX
=> [Chore] Form Toggles Borders & Box Shadows

README.md, projects/go-lib/package.json
Targets v1.11.0
Updates docs and package.json to target v1.12.0
=> [Chore] v1.12.0 Documentation Update

projects/go-lib/src/lib/components/go-select/go-select.component.html, projects/go-lib/src/lib/components/go-select/go-select.component.ts
Resolves #827 
Exposes the ng-select `clearSearchOnAdd` binding and sets the default to `true`.
=> [Bug] go-select Clear On Add

projects/go-lib/src/lib/components/go-action-sheet/go-panel/go-panel.component.scss, projects/go-lib/src/lib/components/go-action-sheet/go-panel/go-panel.component.spec.ts, projects/go-lib/src/lib/components/go-action-sheet/go-panel/go-panel.component.ts, projects/go-style-guide/src/app/features/ui-kit/components/action-sheet-docs/components/action-sheet-panel-docs/action-sheet-panel-docs.component.html, projects/go-style-guide/src/app/features/ui-kit/components/action-sheet-docs/components/action-sheet-panel-docs/action-sheet-panel-docs.component.ts
Resolves #782 
Resolves #784 
Adds the ability to specify a readonly panel and better enforces disabled and readonly states to prevent event emission.
=> [Feature] go-panel Readonly

projects/go-lib/src/lib/components/go-select/go-select.component.html
"Remove All" button on the go-select was not properly rendering and the "Select All" option was showing when all options were selected.
"Remove All" button appears when the control has a value and "Select All" disappears when there are no more items to select.
=> [Bug] go-select Remove All button

projects/go-lib/src/lib/components/go-form-errors/go-form-errors.component.ts, projects/go-lib/src/lib/services/form.service.spec.ts
Form components would not properly render the appropriate error message if the field was invalid.
Properly renders the error messages.
=> [Bug] Form Error Messages

.github/workflows/ci.yml, .github/workflows/version-check.yml
Concurrency is not unique enough and can cancel out other workflows not of the same type.
Fixes described issue by making concurrency groups unique to workflows.
=> Fix CI Concurrency

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md, README.md
Docs referenced `master` branch
Updated to `main` branch
=> Updates references from master to main in docs

projects/go-lib/src/lib/components/go-icon-button/go-icon-button.component.scss
Resolves #846 
Icon Button color is correct
=> [Chore] Icon Button Disabled Color

README.md, projects/go-lib/package.json
Currently targets `v1.13.2`
Updates target to `v1.14`. Removes unnecessary line from docs.
=> [Chore] v1.14 Docs

.github/workflows/cd.yml, projects/go-lib/package.json
Error publishing to npm because of invalid version format
Fixed version format
=> [Fix] v1.14 Invalid Version

.github/workflows/cd.yml, projects/go-lib/package.json
=> Fix v14 CD publish

.github/workflows/cd.yml, projects/go-lib/.npmrc, projects/go-lib/ng-package.json, projects/go-lib/package.json
- Release generated is not using `main` as the target
- Publishing to npm fails
Fixes both of the above.
=> Cd workflow fixes

projects/go-lib/package.json
=> Version Bump

projects/go-lib/src/lib/components/go-card/go-card.component.scss
currently there is a extra padding added to the card header.
Resolves [786](https://github.com/mobi/goponents/issues/786)
should not have extra padding below the header.
=> [Chore] Reduce spacing under header within cards #786

projects/go-lib/src/lib/components/go-modal/go-modal.component.scss, projects/go-lib/src/lib/components/go-off-canvas/go-off-canvas.component.scss, projects/go-lib/src/lib/components/go-timepicker/go-time.component.html, projects/go-lib/src/lib/components/go-timepicker/go-time.component.scss, projects/go-lib/styles/_variables.scss
#863 
#790 
Resolves 
#863 - background overlay color of both off-canvas and modals has been changed to to rgba(0,0,0,.5).
#790  - for time picker minimum width is kept as 9.813rem
=> BUGFIX_TIME_PICKER_ALIGNMENT-CHORE_BACKGROUND_COLOR_CHANGE

projects/go-lib/src/lib/components/go-button/go-button.component.scss
Icon button containing text have additional padding added to the left side.
Resolves 873
Icon button padding alignment done
=> alignment corrected for icon button

projects/go-lib/karma.conf.js, projects/go-lib/src/lib/components/go-select/go-select.component.html, projects/go-lib/src/lib/components/go-select/go-select.component.spec.ts, projects/go-lib/src/lib/components/go-select/go-select.component.ts
=> Bug fix select all filtered list

projects/go-lib/src/lib/components/go-side-nav/go-side-nav/go-side-nav.component.scss, projects/go-lib/src/lib/components/go-side-nav/go-side-nav/go-side-nav.component.spec.ts, projects/go-lib/styles/_variables.scss
App drawer has different styling.
Resolves #927 
##What is the new behavior?
New style has been updated as per doc (#6C757D).
=> Added app-drawer stylings

projects/go-lib/package.json
Updated package.json to have a new version number for release.
Resolves 
N/A
None
=> Updating version number to reflect recent changes

projects/go-lib/package.json
Includes Leap Day calculations fix.
Resolves
=> Update Goponent version

projects/go-lib/package.json
For easier history tracking/bug fixing. Noticed there were several file changes (1 commit) in main but not in dev... thoughts are this is related to the Activity Manager feature Persistent worked on in 2022-2023.
Resolves
=> Update minor version for release

.github/workflows/version-check.yml, projects/go-lib/package.json
=> release 1.18.0 changes

.github/workflows/cd.yml
=> fixed token issue

.github/workflows/cd.yml, projects/go-lib/package.json
=> release 1.18.1

projects/go-lib/styles/_variables.scss, projects/go-style-guide/src/app/features/standards/components/colors/colors.component.html, projects/go-style-guide/src/app/features/standards/components/colors/colors.component.ts
Note: SCSS changes do not need to be implemented directly on the production server. These changes will first be verified on the test server: Preview Link - https://deploy-preview-961--goponents.netlify.app/ui-kit/
=> Revert TOP-5530 From Prod.

projects/go-lib/src/lib/components/go-button/go-button.component.scss, projects/go-lib/styles/_mixins.scss, projects/go-lib/styles/_variables.scss
TOP-5553 and points from feedback doc.
=> TOP-5553 and points from feedback doc.

projects/go-style-guide/src/app/features/standards/components/colors/colors.component.html, projects/go-style-guide/src/app/features/standards/components/colors/colors.component.ts
=> TOP-5558, TOP-5559, TOP-5560
