package-lock.json
package.json

With this update to the gosheets module we will get access to
several new features. v0.7.1 includes styles that will help us
streamline our buttons, icons, and form inputs.
This upgrade also gives us access to several more sass variables
and mixins.
This upgrade shouldn't have any impact on the current goponents
code. However, it will allow us to start changing some things around
in subsequent PRs.

Updates gosheets to version v0.7.1

---

package.json

This should force a more specific version of npm and node. It also
fixes a discrepancy with out version of gosheets.

Specify node and npm engine version

---

projects/go-lib/src/lib/components/go-toast/go-toast.component.html
projects/go-lib/src/lib/components/go-toast/go-toast.component.ts
projects/go-tester/src/app/app.component.ts

There was an issue we were running into when attempting to compile
goponents due to the toast component template not having access
to the functions that are private inside the component.ts file.
This keeps those private, but changes the way we expose those to
the template using static variables. This will fix this issue and
is probably a little bit more performant.

Fixes the way data is exposed to the go-toast component

---

projects/go-lib/src/lib/components/go-table/go-table-config.model.ts

This removes the 'optional' flag on `totalCount` which apparently defaults to `undefined` and sets it to default to `null`.

Total results calculated to NaN

---

projects/go-lib/src/lib/components/go-table/go-table.component.ts

If `sortable == false` on `GoTableConfig`, when column heading clicked to sort `loadingData` was set to `true` before we check if the table is sortable. This results in a persisted loading state with no way to reset it.

Fix loadingData set incorrectly when table not sortable

---

package-lock.json
package.json
projects/go-lib/package.json
projects/go-lib/src/lib/components/go-button/go-button.component.ts
projects/go-tester/src/app/app.component.html

This PR updates us to the latest version of gosheets and adds the functionality for using dark themed buttons within the go-button component through a binding called `useDarkTheme`.

[Feature] Add Ability To Use Dark Theme For Buttons

---

package-lock.json
package.json
projects/go-lib/package.json

The goponents module requires gosheets to work properly. Adding it
to the list of peerDepenencies will make it so a warning pops up
when you try to install one without the other.

Adds gosheets as a peer dependency

---

projects/go-lib/package.json

This represents the first stable release of the goponents module.

Increment to v1.0.0

---

projects/go-lib/src/lib/components/go-icon/go-icon.component.spec.ts
projects/go-lib/src/lib/components/go-icon/go-icon.component.ts

This adds basic unit tests around the `<go-icon>` component and it's corresponding template.

Adds tests for go-icon component

---

projects/go-lib/src/lib/components/go-side-nav/go-nav-group/go-nav-group.component.html
projects/go-lib/src/lib/components/go-side-nav/go-nav-group/go-nav-group.component.scss
projects/go-lib/src/lib/components/go-side-nav/go-nav-group/go-nav-group.component.ts
projects/go-lib/src/lib/components/go-side-nav/go-nav-item/go-nav-item.component.html
projects/go-lib/src/lib/components/go-side-nav/go-nav-item/go-nav-item.component.scss
projects/go-lib/src/lib/components/go-side-nav/go-nav-item/go-nav-item.component.ts
projects/go-lib/src/lib/components/go-side-nav/go-side-nav.module.ts
projects/go-lib/src/lib/components/go-side-nav/go-side-nav/go-side-nav.component.html
projects/go-lib/src/lib/components/go-side-nav/go-side-nav/go-side-nav.component.scss
projects/go-lib/src/lib/components/go-side-nav/go-side-nav/go-side-nav.component.ts
projects/go-lib/src/lib/components/go-side-nav/go-side-nav/go-side-nav.service.ts
projects/go-lib/src/lib/components/go-side-nav/nav-group.model.ts
projects/go-lib/src/lib/components/go-side-nav/nav-item.model.ts
projects/go-lib/src/lib/go-shared.module.ts
projects/go-lib/src/public_api.ts
projects/go-lib/src/styles/_variables.scss
projects/go-tester/src/app/app.component.html
projects/go-tester/src/app/app.component.scss
projects/go-tester/src/app/app.component.ts
projects/go-tester/src/app/app.module.ts
projects/go-tester/src/app/app.router.ts
projects/go-tester/src/app/dummy.component.ts
projects/go-tester/src/styles.scss

This implements a side nav that can be dropped into a layout.
To use it you would drop the side navigation into the app template as the first thing in the content.
```
<go-side-nav [menuItems]="menuItems"></go-side-nav>
```
It takes one parameter which is menuItems which takes a list of things that goes into the side nav. These can either be a group of items or an item. A group would have an array of subRoutes while a normal item would have a route and a routeTitle. The route is the url that the button goes to while the routeTitle is what is displayed on the button. Each item or group on the top level of the navigation needs to have a routeIcon attached to it for the purposes of collapsing the navigation. If a group doesn't have any subroutes it will be hidden by default.
ex list of …

[Feature] Side Navigation

---

projects/go-lib/src/lib/components/go-icon-button/go-icon-button.component.html
projects/go-lib/src/lib/components/go-icon-button/go-icon-button.component.scss
projects/go-lib/src/lib/components/go-icon-button/go-icon-button.component.ts
projects/go-lib/src/lib/components/go-icon-button/go-icon-button.module.ts
projects/go-lib/src/lib/components/go-icon/go-icon.component.spec.ts
projects/go-lib/src/lib/components/go-icon/go-icon.component.ts
projects/go-lib/src/lib/go-shared.module.ts
projects/go-lib/src/public_api.ts
projects/go-tester/src/app/app.component.html
projects/go-tester/src/app/app.module.ts

Creates a component for buttons with icons that do not have text.
Implementation example:
```
<go-icon-button buttonIcon="home" (handleClick)="openThing()"></go-icon-button>
```
@grahamhency - review everything

Adds all files necessary for GoIconButtonComponent

---

projects/go-lib/src/lib/components/go-icon-button/go-icon-button.component.html
projects/go-lib/src/lib/components/go-icon-button/go-icon-button.component.ts
projects/go-tester/src/app/app.component.html

Addresses [#83](https://github.com/mobi/goponents/issues/83)
Adds a `buttonTitle` binding to go-icon-button component which passes its value to the `title` attribute of the button element encapsulated within the go-icon-button, thus enabling tooltips.

Add title attribute to go-icon-button

---

projects/go-lib/src/lib/animations/search.animation.ts

Fixes #81 
In firefox the loading spinner and no results content never go away after they appear. If they get triggered again, the content just gets duplicated. This is happening because of https://github.com/angular/angular/issues/20489. In order to fix it we can just add the base styles on the leave animation instead of relying on the browser to find them.

Firefox Search Animation Errors

---

tslint.json

This updates out linter rules to enforce type definitions on all of the things.
---------------------

Updates linter rules to enforce type definitions everywhere

---

projects/go-lib/src/lib/components/go-table/go-table.component.html
projects/go-lib/src/lib/components/go-table/go-table.component.scss
projects/go-lib/src/lib/components/go-table/go-table.component.ts
projects/go-tester/src/app/components/test-page-1/test-page-1.component.html

To implement this, you need to do two things:
1. Add `[showTableActions]=true` to the `<go-table>` element
2. Provide the elements to appear in the table inside of an element with `go-table-actions` attribute applied
Example:
```
<go-table [tableConfig]="tableConfig" [showTableActions]="true" tableTitle="People Data">
<ng-container go-table-actions>
<go-button>Thing 1</go-button>
<go-icon-button buttonIcon="settings"></go-icon-button>
</ng-container>
<go-table-column field="id" title="ID"></go-table-column>
<go-table-column field="name.first" title="First Name"></go-table-column>
<go-table-column field="name.last" title="Last Name"></go-table-column>
</go-table>
```

Table actions

---

projects/go-lib/src/lib/components/go-action-sheet/go-panel/go-panel.component.html
projects/go-lib/src/lib/components/go-action-sheet/go-panel/go-panel.component.ts
projects/go-tester/src/app/app.component.html
projects/go-tester/src/app/components/test-page-2/test-page-2.component.html

We had an issue with the <go-panel> component where the title @input
was exposing things we didn't want it to because of its naming
collision with the native title attribute. Updating the name of said
attribute to panelContent fixes this issue.

Renames title to panelContent to avoid conflicts with native functionality

---

projects/go-lib/src/lib/components/go-side-nav/go-nav-group/go-nav-group.component.html
projects/go-lib/src/lib/components/go-side-nav/go-nav-group/go-nav-group.component.ts
projects/go-lib/src/lib/components/go-side-nav/nav-group.model.ts

When compiling the html for the navigation we are running into problems because we are checking if property exist, but they only exist for one type of item that we may have. In our component we have a dynamic type that could be either NavItem or NavGroup. We can either switch that type to be any or we can convert that dynamic type to be one of the two types and then do property checks on that.

Compilation Errors Fix

---

projects/go-lib/src/lib/components/go-table/go-table.component.ts

When the GoTable is in client mode, there is no way to access the current local state of the configs (sort direction, page info, etc.). This means that when resetting the `tableConfig` binding to reset the data (for example when you have filtering implemented in the parent component) there is no way to maintain the current state of those configs.
I think ideally there should be a way to trigger the table to rerender without needed to pass in a whole new config object, perhaps exposing some setter methods or something like that, but in the meantime, this PR will allow you to receive the local table config from the `tableChange` event, regardless of what data mode you are, allowing the parent component to be able to use that state when rerendering the table.

GoTable always emits tableChange event, even in client mode.

---

projects/go-lib/src/lib/components/go-table/go-table.component.ts
projects/go-tester/src/app/components/test-page-1/test-page-1.component.ts

This PR updates the go-table-component to not trigger the loading spinner inside of the component for any reason. It will be the responsibility of the parent component to trigger the table updating from here on out.
The parent component can trigger this by updating the loadingData binding in the component
Fixes #107

Update table to not trigger loading inside of table component

---

projects/go-lib/src/lib/components/go-input/go-input.component.html
projects/go-lib/src/lib/components/go-input/go-input.component.spec.ts
projects/go-lib/src/lib/components/go-input/go-input.component.ts
projects/go-lib/src/lib/components/go-input/go-input.module.ts
projects/go-lib/src/lib/go-shared.module.ts
projects/go-lib/src/public_api.ts
projects/go-tester/src/app/app-routing.module.ts
projects/go-tester/src/app/app.component.ts
projects/go-tester/src/app/app.module.ts
projects/go-tester/src/app/components/test-page-3/test-page-3.component.html
projects/go-tester/src/app/components/test-page-3/test-page-3.component.ts

Closes #119 
This adds an input component with a few bindings to allow for the use within reactive forms. It allows you to pass in both hints and errors to be displayed. It puts the responsibility of validation on the parent component allowing the implementor to have full control over the input.

Go Input Component

---

projects/go-lib/src/lib/components/go-text-area/go-text-area.component.html
projects/go-lib/src/lib/components/go-text-area/go-text-area.component.spec.ts
projects/go-lib/src/lib/components/go-text-area/go-text-area.component.ts
projects/go-lib/src/lib/components/go-text-area/go-text-area.module.ts
projects/go-lib/src/lib/go-shared.module.ts
projects/go-lib/src/public_api.ts
projects/go-tester/src/app/app.module.ts
projects/go-tester/src/app/components/test-page-3/test-page-3.component.html
projects/go-tester/src/app/components/test-page-3/test-page-3.component.ts

Closes #120
This adds a textarea component with a few bindings to allow for the use within reactive forms. It allows you to pass in both hints and errors to be displayed. It puts the responsibility of validation on the parent component allowing the implementor to have full control over the textarea.

Go Textarea Component

---

projects/go-lib/src/lib/components/go-accordion/go-accordion-panel.component.html
projects/go-lib/src/lib/components/go-accordion/go-accordion-panel.component.scss
projects/go-lib/src/lib/components/go-accordion/go-accordion-panel.component.spec.ts
projects/go-lib/src/lib/components/go-accordion/go-accordion-panel.component.ts
projects/go-lib/src/lib/components/go-accordion/go-accordion.component.spec.ts
projects/go-lib/src/lib/components/go-accordion/go-accordion.component.ts
projects/go-tester/src/app/components/test-page-1/test-page-1.component.html

This updates the accordion panel to use a simple object in the templates rather than functions. This forces us to manually update when the state changes but increases performance. 
Previous Angular was performing DOM manipulation changes when any event happened. Now it does not because it is more aware of when that happens.

Manually updates classes when state changes to increase performance

---

projects/go-lib/src/lib/components/go-select/go-select.component.html
projects/go-tester/src/app/components/test-page-3/test-page-3.component.html
projects/go-tester/src/app/components/test-page-3/test-page-3.component.ts

Our current implementation defaulted bindValue to be always an ID. Added the missing binding to the go select template so we can change it to whatever we want.

Fixes go select missing bind value

---

projects/go-lib/src/styles/_grid.scss

fixes #161 
This PR introduces a few more modifier classes for the grid system, allowing the user to control the spacing of items in a container using the [justify-content](https://developer.mozilla.org/en-US/docs/Web/CSS/justify-content) property.

Add grid modifiers for justify content

---

projects/go-lib/src/lib/components/go-table/go-table.component.spec.ts
projects/go-lib/src/lib/components/go-table/go-table.component.ts

Fixes #188 
Table page item count was incorrect when last page contained
a number of rows not equal to that of the page size
Removed subtraction of pageCount from calculation logic

[Bug] Table Page Item Count

---

projects/go-lib/src/styles/_forms.scss

Fix dark dropdown which was busted in Chrome on Windows

---

projects/go-lib/src/lib/components/go-toast/go-toast.component.html

The heading element for toasts was not styled correctly. Closes #194 
Applied the `go-heading-5` class to the heading element

[Bug] Fixed Toast Heading Styles

---

projects/go-lib/src/lib/components/go-header/go-header.component.html
projects/go-lib/src/lib/components/go-icon-button/go-icon-button.component.html
projects/go-lib/src/lib/components/go-icon-button/go-icon-button.component.scss
projects/go-lib/src/lib/components/go-icon-button/go-icon-button.component.ts

Menu Icon in the go-header was too small.
Added the ability to specify a size on the go-icon-button which applies the corresponding styles to the go-icon child element. The new binding on the go-icon-button is `buttonSize`.

[Chore] Adjust Menu Icon Size

---

projects/go-lib/src/lib/components/go-header/go-header.component.scss
projects/go-lib/src/lib/components/go-layout/go-layout.component.scss
projects/go-lib/src/styles/_variables.scss

go-side-nav did not scroll vertically when the viewport was not tall enough to fit all of the navigation items. Closes #189 
Set a height attribute on the container within the layout component.

[Bug] Side Nav Doesn't Scroll

---

projects/go-lib/src/lib/components/go-layout/go-layout.component.spec.ts
projects/go-lib/src/lib/components/go-layout/go-layout.module.ts
projects/go-lib/src/lib/components/go-loader/go-loader.module.ts
projects/go-lib/src/lib/components/go-off-canvas/go-off-canvas.module.ts
projects/go-lib/src/lib/components/go-search/go-search.module.ts
projects/go-lib/src/lib/components/go-table/go-table.module.ts
projects/go-lib/src/lib/components/go-toaster/go-toaster.module.ts

Remove BrowserModule + BrowerAnimationModule to address lazy loading issue stated in https://github.com/mobi/goponents/issues/195. This PR does introduce a **breaking change**.
@grahamhency TODO for documentation: State `BrowerAnimationModule` is a required import for animations to work (not sure what the process is for updating it).

[Bug] Remove BrowserModule + BrowerAnimationModule 

---

projects/go-lib/src/lib/components/go-toaster/go-toaster.component.scss

fixes #217 
This PR moves the padding styles from the toaster to the toast items, to avoid the z-index issues. Also I'm using margin instead of padding cuz just seemed more logical.

Use margin on toast item to accomplish padding between toasts

---

projects/go-lib/src/lib/components/go-button/go-button.component.scss
projects/go-lib/src/lib/components/go-off-canvas/go-off-canvas.component.scss
projects/go-lib/src/lib/components/go-search/go-search.component.scss
projects/go-lib/src/lib/components/go-side-nav/go-side-nav/go-side-nav.component.scss
projects/go-lib/src/styles/_forms.scss
projects/go-lib/src/styles/_typography.scss
projects/go-lib/src/styles/_variables.scss
projects/go-style-guide/src/app/app.component.scss
projects/go-style-guide/src/styles/_settings.scss
projects/go-tester/src/styles.scss

Update font stack according to UX spec

---

projects/go-lib/src/lib/components/go-select/go-select.component.html
projects/go-lib/src/lib/components/go-select/go-select.component.ts
projects/go-tester/src/app/components/test-page-3/test-page-3.component.html

Some implementations of select boxes require a placeholder to be designated for that select box. With our current version of the GoSelect component, we are not capable of adding a placeholder value.
The NgSelect module allows us to pass it a placeholder for the select box. This adds the placeholder option as a binding to the GoSelect component and then leverages that binding when creating an NgSelect instance.
I leveraged the [HTML for Template/Header/Footer](https://github.com/ng-select/ng-select/blob/master/src/demo/app/examples/template-header-footer-example/template-header-footer-example.component.html) example that NgSelect provides in order to best implement this solution.

Add Placeholder Binding to GoSelect Component

---

projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/select-docs/select-docs.component.html
projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/select-docs/select-docs.component.ts

Seeing that are looking to add the Placeholder to the GoSelect box in v1.3.0, we should also release with up to date documentation on the GoSelect box that includes implementing the placeholder.
This adds the placeholder documentation to the GoSelect page.

Add Placeholder to GoSelect Documentation

---

CONTRIBUTING.md
PULL_REQUEST_TEMPLATE

We're in the process of changing how we manage branching and deploys in Goponents. 
This PR updates the contribution guide to reflect the process changes. It also adds a PR template that will better help us format our PR descriptions.

[Chore] Update Contribution and PR Template

---

projects/go-lib/src/lib/components/go-select/go-select.component.html
projects/go-lib/src/lib/components/go-select/go-select.component.ts
projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/select-docs/select-docs.component.html
projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/select-docs/select-docs.component.ts
projects/go-tester/src/app/components/test-page-3/test-page-3.component.html
projects/go-tester/src/app/components/test-page-3/test-page-3.component.ts

closes #255 
This adds a `loading` input to our `go-select` so that we can take advantage of `ng-select`'s loading spinner. This will allow us to indicate when the items which will populate a `go-select` dropdown are in the process of being retrieved.

Add loading input to go-select

---

projects/go-lib/src/lib/components/go-table/go-table-column.component.ts
projects/go-lib/src/lib/components/go-table/go-table.component.html
projects/go-lib/src/lib/components/go-table/go-table.component.scss
projects/go-lib/src/lib/components/go-table/go-table.component.spec.ts
projects/go-lib/src/lib/components/go-table/go-table.component.ts
projects/go-style-guide/src/app/features/ui-kit/components/table-docs/components/table-sorting/table-sorting.component.html
projects/go-style-guide/src/app/features/ui-kit/components/table-docs/components/table-sorting/table-sorting.component.ts
projects/go-tester/src/app/components/test-page-1/test-page-1.component.html
projects/go-tester/src/app/components/test-page-1/test-page-1.component.ts

closes #180 
Currently we have the ability to either have every column on a table sortable or none of them. There
are certain cases where we want to be able to just sort by a couple columns on a table. This provides a way for an implementor to decide which columns can be sortable on a table or which columns they want to not be sortable. If a column doesn't contain the sortable binding it will default to whatever is in the table config.

Table Column Sorting

---

projects/go-lib/src/lib/components/go-button/go-button.component.scss
projects/go-tester/src/app/components/test-page-2/test-page-2.component.html

Issue Number: https://github.com/mobi/goponents/issues/171
Button group helper classes were not working due to view encapsulation.
Button helper classes are now exposed again for use.
Closes: https://github.com/mobi/goponents/issues/171

Fix button group helper class not working

---

projects/go-lib/src/lib/components/go-toast/go-toast.component.html
projects/go-style-guide/src/app/features/ui-kit/components/toast-docs/toast-docs.component.html
projects/go-style-guide/src/app/features/ui-kit/components/toast-docs/toast-docs.component.ts
projects/go-tester/src/app/components/test-page-2/test-page-2.component.html

HTML passed into `message` of toast would render as string instead of HTML.
Issue Number: https://github.com/mobi/goponents/issues/239
HTML passed into `message` of toast will render as HTML. Executable HTML is not supported!
Closes: https://github.com/mobi/goponents/issues/239

Support HTML within toast message

---

projects/go-lib/src/lib/components/go-switch-toggle/go-switch-toggle.component.html
projects/go-lib/src/lib/components/go-switch-toggle/go-switch-toggle.component.scss
projects/go-lib/src/lib/components/go-switch-toggle/go-switch-toggle.component.ts
projects/go-tester/src/app/components/test-page-3/test-page-3.component.html
projects/go-tester/src/app/components/test-page-3/test-page-3.component.ts

fixes #233 
Following [material's slide-toggle](https://material.angular.io/components/slide-toggle/api), I named the binding `labelPosition` and set the options as `before` and `after`.

Switch toggle label position

---

projects/go-style-guide/src/app/features/standards/components/grid/grid.component.html
projects/go-style-guide/src/app/features/standards/components/grid/grid.component.ts

We did not have documentation for a 5 column grid layout.
Added it.

[Chore] 5 Column Documentation

---

projects/go-lib/src/lib/components/go-layout/go-layout.component.scss
projects/go-lib/src/styles/_mixins.scss

closes #269 
We need to add an additional option to our `$z-index` function that can be used for loading screens. The new value should be higher than all of the current options to ensure that nothing will appear on top of anything utilizing this option for its `z-index`.

Chore z index for load screen

---

projects/go-lib/src/lib/animations/accordion.animation.ts
projects/go-lib/src/lib/components/go-accordion/go-accordion-panel.component.scss
projects/go-tester/src/app/components/off-canvas-test/off-canvas-test.component.html
projects/go-tester/src/app/components/off-canvas-test/off-canvas-test.component.ts

Closes #143 
This PR addresses an issue in which GoSelect dropdowns are getting cutoff when their content expands below the bottom edge of a GoAccordionPanel. This was being caused by an `overflow: hidden` on the `.go-accordion-panel` css class. We can change this to `overflow: visible`, thus enabling the dropdown content to no longer get cut off, while also modifying the animation which occurs on expansion and collapse of a GoAccordionPanel to achieve the same effect as was provided by `overflow: hidden` previously.

BUG: fix go-select dropdowns being cut off in go-accordian-panels

---

projects/go-lib/src/lib/components/go-button/go-button.component.html
projects/go-lib/src/lib/components/go-button/go-button.component.scss
projects/go-lib/src/lib/components/go-button/go-button.component.spec.ts
projects/go-lib/src/lib/components/go-button/go-button.component.ts
projects/go-lib/src/lib/components/go-button/go-button.module.ts
projects/go-lib/src/lib/components/go-icon/go-icon.component.scss
projects/go-lib/src/lib/components/go-loader/go-loader.component.scss
projects/go-lib/src/lib/components/go-loader/go-loader.component.spec.ts
projects/go-lib/src/lib/components/go-loader/go-loader.component.ts
projects/go-style-guide/src/app/features/ui-kit/components/button-docs/button-docs.component.html
projects/go-style-guide/src/app/features/ui-kit/components/button-docs/button-docs.component.ts

We have button variants for:
- `positive`
- `negative`
- `neutral`
Issue Number: Closes #170 
We have button variants for:
- primary (replacing positive)
- `secondary`
- `tertiary`
- `neutral`
- `negative`
There are two changes that could be considered "breaking".
1. The `alert` variant is being removed. This was already deprecated in a previous version, but is officially being removed now.
- Any instances of `alert` that remain should be changed to `negative`
2. The `positive` variant is being removed, however, we are going to accept it as a variant and change it to `primary` for now. In this case, it's not functionality breaking, but possibly UX breaking.
- Not all `positive` buttons will need to be `primary`. In that case, the buttons labeled …

[Chore] Button Design Update

---

projects/go-lib/src/lib/components/go-select/go-select.component.html
projects/go-lib/src/lib/components/go-select/go-select.component.ts
projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/select-docs/select-docs.component.html
projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/select-docs/select-docs.component.ts
projects/go-style-guide/src/app/features/ui-kit/ui-kit.module.ts
projects/go-tester/src/app/app.component.ts
projects/go-tester/src/app/app.module.ts

Closes #246 
Currently, making a selection on a `go-select` within a `go-modal` causes the modal to close. Sometimes we might desire that the `go-modal` remain open until a submission button is clicked, for instance.
By adding an `appendTo` input to our `go-select` and passing it to the `appendTo` input of the contained `ng-select`, we can make it so that a `go-modal` will remain open upon making a selection to a `go-select` within it using `appendTo="'body'"`.
Example:
```
openModal(): void {
this.goModalService.openModal(
GoSelectComponent,
{
appendTo: 'body',
bindLabel: 'name',
bindValue: 'value',
control: this.select10,
items: this.items,
label: 'Favorite Candy',
}
);
}
```

Add appendTo input to go-select

---

projects/go-style-guide/src/app/features/ui-kit/components/loader-docs/loader-docs.component.html
projects/go-style-guide/src/app/features/ui-kit/components/loader-docs/loader-docs.component.ts

We were missing documentation around the dark and light loader options that were added.
Added docs for them.
Closes #244

[Chore] Loader Type Docs

---

projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/radio-button-docs/radio-button-docs.component.html
projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/radio-button-docs/radio-button-docs.component.ts
projects/go-style-guide/src/app/features/ui-kit/components/form-docs/form-docs.component.ts
projects/go-style-guide/src/app/features/ui-kit/routes/ui-kit-routing.module.ts
projects/go-style-guide/src/app/features/ui-kit/ui-kit.module.ts

We were missing documentation for the `go-radio-button` and `go-radio-group` components. 
Added the missing documentation.
Closes #225, #224

[Chore] Radio Button Documentation

---

projects/go-lib/src/lib/components/go-checkbox/go-checkbox.component.html
projects/go-lib/src/lib/components/go-checkbox/go-checkbox.component.spec.ts
projects/go-style-guide/src/app/features/ui-kit/components/button-docs/button-docs.component.html
projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/checkbox-docs/checkbox-docs.component.html
projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/checkbox-docs/checkbox-docs.component.ts
projects/go-style-guide/src/app/features/ui-kit/components/form-docs/form-docs.component.ts
projects/go-style-guide/src/app/features/ui-kit/routes/ui-kit-routing.module.ts
projects/go-style-guide/src/app/features/ui-kit/ui-kit.module.ts

We did not have documentation covering the `go-checkbox` or the `go-checkbox-group` components.
Added documentation for both components.
Closes #228, #227

[Chore] Checkbox Documentation

---

projects/go-lib/src/lib/components/go-datepicker/date-adapter.ts

Issue Number: https://github.com/mobi/goponents/issues/277
Date adapter incorrectly formats dates for users in different timezones.
Date adapter correctly formats dates based on users timezone.
(not sure honestly)

[Bugfix] Go-Datepicker: Set timezone based on user's settings

---

projects/go-lib/src/lib/components/go-table/go-table.component.html

Sets the value of the dropdown based on `localTableConfig`
fixes #292

Control state of per page dropdown from table config

---

projects/go-lib/src/lib/components/go-select/go-select.component.html
projects/go-lib/src/lib/components/go-select/go-select.component.ts
projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/select-docs/select-docs.component.html
projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/select-docs/select-docs.component.ts

Adds the ability to use a typeahead with go-select through the `typeahead` binding. This allows for things like fetching the results server side from a user searching for results.
closes #280

Go Select Async Items

---

package-lock.json
package.json

Currently when running tests there is a `'Setting specFilter directly on Env is deprecated, please use the specFilter option in configure'` warning. This is happening because of the karma-jasmine version and has been fixed in a later release.
No warnings or errors in tests

Update Karma Jasmine Version

---

projects/go-lib/src/lib/components/go-accordion/go-accordion-panel.component.ts
projects/go-lib/src/lib/components/go-accordion/go-accordion.component.ts

Issue Number: https://github.com/mobi/goponents/issues/303
We're updating the accordion panel from the accordion after it's initialized. The problem with this is in production mode there isn't another lifecycle trigger after we change this and those changes won't get picked up by the browser. This can be fixed by manually triggering the change detection cycle after we update it so that the changes are picked up.

Accordion Expression Changed After Checked

---

projects/go-lib/src/lib/components/go-modal/go-modal.component.html
projects/go-lib/src/lib/components/go-modal/go-modal.component.scss
projects/go-lib/src/lib/components/go-modal/go-modal.component.ts
projects/go-style-guide/src/app/features/ui-kit/components/modal-docs/modal-docs.component.html
projects/go-style-guide/src/app/features/ui-kit/components/modal-docs/modal-docs.component.ts
projects/go-style-guide/src/app/features/ui-kit/components/modal-test/modal-test.component.html
projects/go-style-guide/src/app/features/ui-kit/components/modal-test/modal-test.component.ts

Currently the modal does not support the ability for a title to be on the same line as `x` and does not support fixed size requirements per UX design.
Issue Number: https://github.com/mobi/goponents/issues/313
Two new binding have been added to modal: `modalTitle` and `modalSize`
If any component is using `modalTitle` or `modalSize` as part of their object binding to component, it may cause undesirable results.
N/A

[Feature] Support title and sizes for modal 

---

projects/go-lib/src/lib/components/go-accordion/go-accordion-panel.component.html
projects/go-lib/src/lib/components/go-accordion/go-accordion-panel.component.spec.ts
projects/go-lib/src/lib/components/go-accordion/go-accordion-panel.component.ts
projects/go-style-guide/src/app/features/ui-kit/components/accordion-docs/components/accordion-panel-docs/accordion-panel-docs.component.html
projects/go-style-guide/src/app/features/ui-kit/components/accordion-docs/components/accordion-panel-docs/accordion-panel-docs.component.ts
projects/go-style-guide/src/app/features/ui-kit/components/accordion-docs/components/accordion-panel-docs/loading-test.component.ts
projects/go-style-guide/src/app/features/ui-kit/ui-kit.module.ts
projects/go-tester/src/app/components/off-canvas-test/off-canvas-test.component.html

Accordions will always load anything inside of it into the dom when it's loaded. This causes content that may never be rendered on the page to be loaded when the page is initialized, which is inefficient. Ideally we would be able to not load this content until the accordion is actually opened.
There is an option depending on how you initialize the accordion to not load the content of an accordion panel until it's clicked on. This is done through the use of ng-template and will require an extra line when writing the html for each accordion pane. 
There are no breaking changes, but going forward new accordion panels should probably be written with the ng-template instead of relying on …

Prevent Accordion Content from Initializing Before Opened

---

projects/go-lib/src/lib/components/go-table/go-table-page.model.ts
projects/go-lib/src/lib/components/go-table/go-table.component.html
projects/go-lib/src/lib/components/go-table/go-table.component.scss
projects/go-lib/src/lib/components/go-table/go-table.component.spec.ts
projects/go-lib/src/lib/components/go-table/go-table.component.ts

Issue Number: https://github.com/mobi/goponents/issues/236
On the go-table if there is pagination there will be 5 pages that show up at a time in the page numbers. They will be centered around the active page unless that page is one of the first two pages or last two pages and then it will just have the first or last 5 pages showing.

Add Page Numbers to Pagination

---

projects/go-lib/src/lib/components/go-modal/go-modal.component.scss
projects/go-lib/src/styles/_variables.scss
projects/go-style-guide/src/app/features/ui-kit/components/modal-docs/modal-docs.component.html
projects/go-style-guide/src/app/features/ui-kit/components/modal-docs/modal-docs.component.ts

Issue Number: https://github.com/mobi/goponents/issues/313
An extension of changes made in PR https://github.com/mobi/goponents/pull/321
Currently `lg` always expands to the size of `xl` since the `max-width` was set equal to the size of `xl`. This is something I accidentally introduced in https://github.com/mobi/goponents/pull/321 😄 but luckily caught it before it was released. 
Also added additional documentation to showcase the different available sizes.  
N/A

Fix modal sizes and add additional documentation for modal sizes

---

projects/go-lib/src/lib/components/go-modal/go-modal.component.spec.ts
projects/go-lib/src/lib/components/go-modal/go-modal.component.ts

Can't catch a break with this change 😅. Since `GoModalComponent` is being treated as a singleton via `GoModalService` - the values are persisting between different modals. For example if I execute
```
this.goModalService.openModal(ModalTestComponent, { modalTitle: 'XL Modal', modalSize: 'xl', content: 'This is a xl modal' });
```
and then execute
```
this.goModalService.openModal(ModalTestComponent, { content: 'This is a lg modal' });
```
One would expect the second modal to have a title of `''` and a size of `lg`. However, currently the second modal is persisting the values from first modal. 
Since this feature has not been released yet, I'm referencing the initial issue to add the …

go-modal: Reset defaults on new component load

---

projects/go-lib/src/lib/components/go-switch-toggle/go-switch-toggle.component.html
projects/go-lib/src/lib/components/go-switch-toggle/go-switch-toggle.component.scss

When the label text for a switch toggle is too long to fit within the width of its parent, it gets pushed down below the toggle.
Issue Number: #354 
With this PR, the label text is now positioned correctly regardless of its length.

Fix switch toggle label placement

---

projects/go-lib/src/styles/_grid.scss
projects/go-style-guide/src/app/features/standards/components/grid/grid.component.html
projects/go-style-guide/src/app/features/standards/components/grid/grid.component.ts
projects/go-style-guide/src/app/features/ui-kit/components/basic-test/basic-test.component.html
projects/go-style-guide/src/app/features/ui-kit/components/basic-test/basic-test.component.scss

Our `.go-container` class provides negative left and right margin to avoid excessive left and right spacing from stacking up around elements with `.go-column`. This is needed because `.go-container` is generally used within elements that provide left and right spacing, and thus the left and right padding provided by `.go-column` would be added to that spacing in the absence of the negative margin provided by `.go-container`, which is not what we want.
The problem is that there are some cases in which we want to use `.go-container` within a context that does *not* provide any left and right spacing, and so the negative margin of `go-container` cancels out the left ad right padding of …

Add Container Reset Class

---

projects/go-lib/src/lib/components/go-datepicker/calendar-views.scss

Some of the font-colors for our go-datepicker inherit from their parent and thus are turned white when their parent uses our dark theme, making the font illegible on the white background of the datepicker.
Issue Number: #363 
The font-colors of the datepicker are now set to black so that they are always visible on the white background of the datepicker.
- [ x] No

Fix datepicker font-colors for dark theme

---

projects/go-lib/src/lib/components/go-copy/go-copy.component.html
projects/go-lib/src/lib/components/go-copy/go-copy.component.scss
projects/go-lib/src/lib/components/go-copy/go-copy.component.spec.ts

When implementing a copy button inside of a column the icon will always be on the line after the content instead of beside it. The icon is also not clickable.
Make the element an inline element so that it won't appear on the next line. Make the copy icon appear clickable by making the cursor a pointer.

Update Copy Button Styles

---

projects/go-lib/src/lib/components/go-file-upload/go-file-upload.component.html
projects/go-lib/src/lib/components/go-input/go-input.component.html
projects/go-lib/src/lib/components/go-select/go-select.component.html
projects/go-lib/src/lib/components/go-switch-toggle/go-switch-toggle.component.html
projects/go-lib/src/lib/components/go-text-area/go-text-area.component.html

Our form input components render an empty label element when no value is passed into their label input, which creates unwanted spacing above those inputs.
Issue Number: #369 
When no `label` value is provided to our form components, no `label` element is rendered.

Fix Empty Label Elements on Input Components

---

projects/go-lib/src/lib/components/go-text-area/go-text-area.component.html
projects/go-lib/src/lib/components/go-text-area/go-text-area.component.ts
projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/text-area-docs/text-area-docs.component.html
projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/text-area-docs/text-area-docs.component.ts

We currently have no means by which to modify the default height of a `go-text-area`.
Issue Number: #380 
We can now use the `rows` input to specify the default height of a `go-text-area`.

Add row input to text-area

---

projects/go-lib/src/lib/components/go-accordion/go-accordion-panel.component.html
projects/go-lib/src/lib/components/go-accordion/go-accordion-panel.component.scss
projects/go-lib/src/lib/components/go-accordion/go-accordion-panel.component.ts
projects/go-lib/src/lib/components/go-table/go-table.component.html
projects/go-lib/src/lib/components/go-table/go-table.component.scss
projects/go-lib/src/lib/components/go-table/go-table.component.ts
projects/go-style-guide/src/app/features/ui-kit/components/accordion-docs/components/accordion-panel-docs/accordion-panel-docs.component.html
projects/go-style-guide/src/app/features/ui-kit/components/accordion-docs/components/accordion-panel-docs/accordion-panel-docs.component.ts
projects/go-style-guide/src/app/features/ui-kit/components/table-docs/components/table-overview/table-overview.component.html
projects/go-style-guide/src/app/features/ui-kit/components/table-docs/components/table-overview/table-overview.component.ts

Issue Number: https://github.com/mobi/goponents/issues/359
`go-table` supports a new binding `renderBoxShadows` and `go-accordion-panel` supports a new binding `removeContentPadding`. These two bindings when used together will allow users to have a table "flush" within a accordion.
N/A

Table in accordion

---

projects/go-lib/src/lib/components/go-radio/go-radio-button.component.html
projects/go-lib/src/lib/components/go-radio/go-radio-button.component.scss
projects/go-lib/src/lib/components/go-radio/go-radio-button.component.ts
projects/go-lib/src/lib/components/go-radio/go-radio-group.component.spec.ts
projects/go-lib/src/lib/components/go-radio/go-radio-group.component.ts

Issue Number: https://github.com/mobi/goponents/issues/234
This PR addresses two things:
1. Update radio button styles per DSM guidelines
2. Fix a bug where if there were multiple radio groups with the same value, the value would be selected in all groups. This issue can be seen today in the design system example. Issue was occurring because a unique name per group was missing. I'm creating a name using a random generator instead of asking for a key to avoid having any new inputs to the component as well as support backward compatibility.
1. Radio button styles updated
2. `name` added to each radio grouping
N/A

Update go-radio styles + address bug with multiple radio groupings

---

projects/go-lib/src/lib/components/go-accordion/go-accordion-panel.component.html
projects/go-lib/src/lib/components/go-accordion/go-accordion-panel.component.ts
projects/go-style-guide/src/app/features/ui-kit/components/accordion-docs/components/accordion-panel-docs/accordion-panel-docs.component.html
projects/go-style-guide/src/app/features/ui-kit/components/accordion-docs/components/accordion-panel-docs/accordion-panel-docs.component.ts

Issue Number: #417 
You can now use Angular's Content Projection to pass in additional HTML into the header of a `go-accordion-panel`.

[Chore] Adds Content Projection to Accordion Panel

---

projects/go-lib/src/lib/components/go-datepicker/go-datepicker.component.spec.ts
projects/go-lib/src/lib/components/go-datepicker/locale-format.ts

Issue Number: https://github.com/mobi/goponents/issues/382
A user can't type in a year that has more than 4 digits

Validates that year on datepicker is 4 or less digits

---

projects/go-lib/src/lib/components/go-header-bar/go-header-bar.component.spec.ts
projects/go-lib/src/lib/components/go-header-bar/go-header-bar.component.ts

If the go-layout is used in multiple components instead of just one spot with the routing, there is an objectUnsubscribedError when switching routes. This is happening because we are unsubscribing from a behaviorSubject instead of unsubscribing from the actual subscription itself in the go-header-bar component.
There is no object unsubscribed error when switching routes

Object Unsubscribed Error

---

projects/go-lib/src/lib/components/go-icon-button/go-icon-button.component.html
projects/go-lib/src/lib/components/go-icon-button/go-icon-button.component.scss

We currently can disable a `go-icon-button` with the `buttonDisabled` binding, but there is no visual change in the UI and it appears as though you can still click the button.
Issue Number: #376 
When `buttonDisabled` is true, the visual appearance of the `go-icon-button` changes so that it doesn't seem like you can click it.

Add Visual Disabled State to GoIconButton

---

projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/select-docs/select-docs.component.html

Issue Number: #432 
We now reference "select" in the places we were referencing "textarea"

[Chore] Remove textarea from select docs

---

projects/go-lib/src/lib/components/go-datepicker/go-datepicker.component.html
projects/go-lib/src/lib/components/go-datepicker/go-datepicker.component.spec.ts
projects/go-lib/src/lib/components/go-datepicker/go-datepicker.component.ts

Currently when adding the disabled attribute to a datepicker it doesn't disable the input field or the button to open the calendar.
This disables the input field and the button to open the calendar if the form control is disabled

Disable Datepicker

---

projects/go-lib/src/lib/components/go-accordion/go-accordion-panel.component.html
projects/go-lib/src/lib/components/go-accordion/go-accordion-panel.component.scss
projects/go-style-guide/src/app/features/ui-kit/components/accordion-docs/components/accordion-panel-docs/accordion-panel-docs.component.html
projects/go-style-guide/src/app/features/ui-kit/components/accordion-docs/components/accordion-panel-docs/accordion-panel-docs.component.ts

The `accordion-panel` has the ability to project content into the header. Currently, the content was being forced to the right every time.
The `accordion-panel` now projects content into the available space in the header

[Bug] Accordion Panel Content Positioning

---

projects/go-lib/src/lib/components/go-select/go-select.component.html
projects/go-lib/src/lib/components/go-select/go-select.component.ts
projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/select-docs/select-docs.component.html
projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/select-docs/select-docs.component.ts

go-selects by default are "searchable", meaning they have a local typeahead feature. This PR exposed the `searchable` input from ng-select to control that behavior. 
Issue Number: #412

Add searchable input to go-select

---

projects/go-lib/src/lib/components/go-action-sheet/go-action-sheet.component.scss
projects/go-lib/src/lib/components/go-action-sheet/go-action-sheet.component.ts
projects/go-lib/src/lib/components/go-action-sheet/go-panel/go-panel.component.html
projects/go-lib/src/lib/components/go-side-nav/go-side-nav.module.ts
projects/go-lib/src/lib/components/go-side-nav/go-side-nav/go-side-nav.component.html
projects/go-lib/src/lib/components/go-side-nav/go-side-nav/go-side-nav.component.scss
projects/go-lib/src/lib/components/go-side-nav/go-side-nav/go-side-nav.component.spec.ts
projects/go-lib/src/lib/components/go-side-nav/go-side-nav/go-side-nav.component.ts
projects/go-lib/src/lib/components/go-side-nav/nav-app-drawer.model.ts
projects/go-lib/src/public_api.ts
projects/go-style-guide/src/app/app.component.html
projects/go-style-guide/src/app/app.component.ts
projects/go-style-guide/src/app/features/ui-kit/components/action-sheet-docs/components/action-sheet-overview/action-sheet-overview.component.html
projects/go-style-guide/src/app/features/ui-kit/components/action-sheet-docs/components/action-sheet-overview/action-sheet-overview.component.ts
projects/go-style-guide/src/app/features/ui-kit/components/action-sheet-docs/components/action-sheet-panel-docs/action-sheet-panel-docs.component.html
projects/go-style-guide/src/app/features/ui-kit/components/layout-docs/components/layout-app-drawer/layout-app-drawer.component.html
projects/go-style-guide/src/app/features/ui-kit/components/layout-docs/components/layout-app-drawer/layout-app-drawer.component.ts
projects/go-style-guide/src/app/features/ui-kit/components/layout-docs/components/layout-nav/layout-nav.component.html
projects/go-style-guide/src/app/features/ui-kit/components/layout-docs/components/layout-nav/layout-nav.component.ts
projects/go-style-guide/src/app/features/ui-kit/components/layout-docs/layout-docs.component.ts
projects/go-style-guide/src/app/features/ui-kit/routes/ui-kit-routing.module.ts
projects/go-style-guide/src/app/features/ui-kit/ui-kit.module.ts

Issue Number: https://github.com/mobi/goponents/issues/60
This PR introduces an app-drawer referencing the design here: https://tangoe.invisionapp.com/share/JCT2JAKXTQ9#/screens/374819807_Cloud_-_Expanded
It's not a 1:1 match yet, but this PR provides all current expected functionality. Changes to design will be discussed with UX team.
N/A

[Feature] App drawer support within side navigation

---

projects/go-lib/src/lib/components/go-modal/go-modal.component.scss

Currently the modal can extend beyond the edge of the page if there is too much content
Closes #476 
It stops at 100% of the available height and then scrolls

[Bugfix] Modal Height Extends Beyond Page

---

projects/go-lib/src/lib/components/go-table/go-table.component.spec.ts
projects/go-lib/src/lib/components/go-table/go-table.component.ts

The `searchTerm` on the table search is being subscribed to on every `onChange` event. Causing an extreme amount of excess events to be called the more the table search is used.
Moved the `searchSetup` method into the `ngOnInit` instead of in `ngOnInit` so that we only subscribe to the changes once.

[Bug] Table Search Subscription

---

projects/go-lib/src/lib/components/go-select/go-select.component.spec.ts
projects/go-lib/src/lib/components/go-select/go-select.component.ts

~Docs have been added / updated (for bug fixes / features)~
Currently if we are storing the value of the item in the go select on a key other then value and select all is clicked there are empty values attached to the go-select instead of grabbing the values based on the key that bindValue maps to.
If there is a bindValue that is passed in, we use that as the key to get the value of the item, otherwise we select the entire object, which is the default that ng-select uses.

Go Select Select All Bind Value Errors

---

projects/go-lib/src/lib/components/go-modal/go-modal.component.html
projects/go-lib/src/lib/components/go-modal/go-modal.component.scss
projects/go-lib/src/lib/components/go-modal/go-modal.component.spec.ts
projects/go-lib/src/lib/components/go-modal/go-modal.component.ts
projects/go-lib/src/lib/components/go-modal/go-modal.module.ts
projects/go-style-guide/src/app/features/ui-kit/components/modal-docs/modal-docs.component.html
projects/go-style-guide/src/app/features/ui-kit/components/modal-docs/modal-docs.component.ts

The modal content has a persistent padding. This makes it difficult in some instances to get correct alignment.
Closes #496 
Adds a `noContentPadding` binding that defaults to `false`

[Chore] Add ability to remove modal content padding

---

projects/go-lib/src/lib/components/go-datepicker/go-calendar.ts
projects/go-lib/src/lib/components/go-modal/go-modal.service.ts
projects/go-lib/src/lib/components/go-off-canvas/go-off-canvas.service.ts

There were a couple of places in the `go-lib` project where we imported `Subject` from `rxjs/internals/subject` instead of the base `rxjs` directory. Angular 9 apps will yell at us about this.
Closes #493 
Changed the imports to import from `rxjs`

[Chore] Update where rxjs Subject is imported from

---

projects/go-lib/src/lib/components/go-select/go-select.component.html
projects/go-lib/src/lib/components/go-select/go-select.component.ts
projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/select-docs/select-docs.component.html
projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/select-docs/select-docs.component.ts

The "Select All" button always shows up when the `go-select` has the `[multiple]="true"` binding.
Closes #495 
There is a new binding `[showSelectAll]` that can be passed in that will hide the "Select All" button.

[Chore] Add ability to hide the "select all" button on multiple select

---

projects/go-lib/src/lib/components/go-table/go-table.component.scss

When you have a lot of filter pills in the table, the get all squished together instead of wrapping to the next line:
Adding the flex-wrap property allows for the pills to wrap nicely:

allow filter pills in table to wrap

---

projects/go-lib/src/lib/components/go-tab/go-tab-group.component.scss

Tab headers have `.5rem` vertical padding
Closes #502 
Adjusted padding to `.75rem` vertically

[Chore] Tab Header Padding

---

projects/go-lib/src/lib/components/go-side-nav/go-side-nav/go-side-nav.component.spec.ts
projects/go-lib/src/lib/components/go-side-nav/go-side-nav/go-side-nav.component.ts
projects/go-lib/src/lib/components/go-side-nav/nav-group.model.ts

When clicking a NavGroup item within a `go-side-nav`, if there are other NavGroups with the same `routeTitle`, those accordions will be expanded in addition to the one that was clicked.
Issue Number: #512 
We can generate an `id` for each NavGroup and then use those, rather than the `routeTitle`s, when checking which NavGroups to expand/close upon clicking a NavGroup.

Fix Multiple Side-Nav Accordions Opening Simultaneously

---

projects/go-lib/src/lib/components/go-action-sheet/go-panel/go-panel.component.html
projects/go-lib/src/lib/components/go-action-sheet/go-panel/go-panel.component.spec.ts
projects/go-lib/src/lib/components/go-action-sheet/go-panel/go-panel.component.ts

Currently the `go-action-sheet` does not close when a user clicks on a `go-panel` inside.
Closes #514 
When a user clicks on a `go-panel` inside of a `go-action-sheet` it will close the `go-action-sheet` regardless if the `go-panel` is a link or an action.

[Chore] Close Action Sheet on Panel Click

---

projects/go-lib/src/lib/components/go-datepicker/day-view/go-calendar-day-view.component.html
projects/go-lib/src/lib/components/go-datepicker/go-calendar.component.html
projects/go-lib/src/lib/components/go-datepicker/go-calendar.component.scss
projects/go-lib/src/lib/components/go-datepicker/go-calendar.component.ts
projects/go-lib/src/lib/components/go-datepicker/go-calendar.ts
projects/go-lib/src/lib/components/go-datepicker/go-datepicker.component.html
projects/go-lib/src/lib/components/go-datepicker/go-datepicker.component.scss
projects/go-lib/src/lib/components/go-datepicker/go-datepicker.component.spec.ts
projects/go-lib/src/lib/components/go-datepicker/go-datepicker.component.ts
projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/datepicker-docs/datepicker-docs.component.html
projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/datepicker-docs/datepicker-docs.component.ts

Issue Number: #511 
Adds a new binding for the datepicker to allow for appending to the content instead of showing the calendar over the content on the page.
* Small bugfix where clicking in between two dates, or clicking at the beginning of the month or end of the month where there are no days would close the calendar and error
* Small bugfix where clicking on the calendar icon once the calendar is open wouldn't close the calendar

Datepicker Overflow in Modals

---

projects/go-lib/src/lib/components/go-icon/go-icon.component.scss
projects/go-lib/src/lib/components/go-icon/go-icon.component.ts
projects/go-style-guide/src/app/features/ui-kit/components/icon-docs/icon-docs.component.html
projects/go-style-guide/src/app/features/ui-kit/components/icon-docs/icon-docs.component.ts

Issue Number: #525 
Added the ability to pass 'positive', 'negative', and 'neutral' to the the `iconModifier` binding of `go-icon`, which alter the color of the icon.

Add positive, negative, and neutral options to iconModifier of go-icon

---

projects/go-lib/src/lib/components/go-side-nav/go-nav-item/go-nav-item.component.ts

Issue Number: #540 
Adding `attributes` to `go-nav-item`s throws a console error and causes the sub-navs in which they appear to fail to render correctly.
Able to add `attributes` to `go-nav-item`s without throwing an error.

Fix console error when setting custom attributes on go-nav-items

---

projects/go-lib/src/styles/_typography.scss

Currently using the go-link class from goponents does not produce a link that looks the same as links in the style guide do. This is because in the style guide we have a style in there that removes the text decoration from all link tags.
We remove the bottom border from go-link and add text decoration to make all the same styles are being applied to link tags in the style guide.

Removes text decoration from go-link

---

projects/go-lib/src/styles/_globals.scss
projects/go-style-guide/src/app/features/ui-kit/components/card-docs/card-docs.component.html
projects/go-style-guide/src/app/features/ui-kit/components/card-docs/card-docs.component.ts

Issue Number: #520 
Classes for styling `hr`s within `go-card`s have been added, both for when the `hr` should span the full width of the card and when it should respect the card's padding.

Add classes for horizontal rules within go-cards

---

projects/go-lib/src/lib/components/go-off-canvas/go-off-canvas.component.scss

Color change
Currently, we are having issues in Mobile where the header for the Go Off Canvas is showing as
dark rather than white by default. This commit should fix this.
Header appears as white instead of dark

BUGFIX: Go Off Canvas Header Color in Mobile

---

projects/go-lib/src/lib/components/go-table/go-table.component.spec.ts
projects/go-lib/src/lib/components/go-table/go-table.component.ts

If you update 
Issue Number: #551 
SearchTerm will show in searchbar even if programmatically set after table is initialized.

Set searchTerm value even if passed in after init

---

projects/go-lib/src/lib/components/go-table/go-table.component.spec.ts
projects/go-lib/src/lib/components/go-table/go-table.component.ts

When entering a search term on a table that is in server mode, the page offset does not get reset. This is resulting in a bug where the api is being called with an offset that is larger than the filtered dataset, resulting in no data being shown.
Issue Number: I'm too lazy to rewrite this info in an issue.
This PR resets the page offset before emitting the table change event, as is being done when the table is in client mode.
I was listening to the Game of Thrones soundtrack while fixing this bug. It helped.

Reset page offset when doing remote search

---

package.json

We are running `npm pack` before publishing. `npm pack` is meant for local testing, and the resulting tarball has no effect on the package when other apps install from npm. So although there is no harm done, it is just an unnecessary step.
Issue Number: #51 
The publish script does not call `npm pack`
I have nothing useful to add here. Sorry.

Remove publishing tarball

---

projects/go-lib/src/lib/components/go-table/go-table.component.spec.ts
projects/go-lib/src/lib/components/go-table/go-table.component.ts

Currently the table rerenders (using `this.renderTable`) on any change to the component. This is causing an issue when a property other that `tableConfig` changes (e.g. `isLoading`). 
For example, if the table is in server mode, and the user types in a search, we want to set `isLoading` to true while we are making the api call with the search term. In the meantime, since `isLoading` changed, the table will will call `renderTable` and use the _existing table config_, which may contain the _previous_ search term, and will just reset the search box to the previous value.
Issue Number: this is a big issue 😉 
This PR adds a guard clause to only call `this.renderTable` in the event that the …

Only rerender table if tableConfig changes

---

projects/go-lib/src/lib/components/go-copy/go-copy-doc-link.directive.spec.ts
projects/go-lib/src/lib/components/go-copy/go-copy-doc-link.directive.ts
projects/go-lib/src/lib/components/go-copy/go-copy.component.scss
projects/go-lib/src/lib/components/go-copy/go-copy.module.ts
projects/go-lib/src/styles/_typography.scss

Issue Number: #558 
This PR adds a directive which, when added to `go-copy` element within a `go-card-header`, enables it to function as a copy-permalink feature for our style-guide.
Example usage:
```html
<go-card class="go-column go-column--100" id="default">
<header go-card-header>
<h2 class="go-heading-2 go-heading--inline">Default</h2>
<go-copy cardId="default" goCopyDocLink></go-copy>
</header>
<div go-card-content>
</div>
</go-card>
```

Add directive for use in adding ability to copy permalinks to doc examples

---

projects/go-lib/src/lib/components/go-button/go-button.component.html
projects/go-lib/src/lib/components/go-button/go-button.component.scss
projects/go-lib/src/lib/components/go-button/go-button.component.spec.ts
projects/go-lib/src/lib/components/go-button/go-button.component.ts

Issue Number: #563 
This is a css only approach to fixing #563. The current solution introduced in #568 uses ViewChild to check if the DOM node has text, and is being accessed in `ngOnInit` which does not work in Angular 9.

Use css only to manage padding for button

---

projects/go-lib/src/lib/components/go-select/go-select.component.html
projects/go-lib/src/lib/components/go-select/go-select.component.ts
projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/select-docs/select-docs.component.html
projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/select-docs/select-docs.component.ts
projects/go-tester/src/app/components/test-page-3/test-page-3.component.html
projects/go-tester/src/app/components/test-page-3/test-page-3.component.ts

ng-select allows passing a template to customize an optgroup label, but it does not work in the current structure of go-select.
This PR exposes that functionality through the go-select component.
I'm wondering if we would have been better off just shipping a custom template for ng-select instead of wrapping it up. I am sure issues like this will keep coming up for any feature in ng-select that will require our component to either be structured in a certain way or explicitly expose it like we needed to do here.

Go select optgroup custom template

---

projects/go-lib/src/lib/components/go-side-nav/go-nav-item/go-nav-item.component.html
projects/go-lib/src/lib/components/go-side-nav/nav-item.model.ts
projects/go-style-guide/src/app/features/ui-kit/components/layout-docs/components/layout-nav/layout-nav.component.ts
projects/go-tester/src/app/components/layout/layout.component.ts

If the `target` of any "externalLink" in the side nav was set to something unique (not a default value provided by browsers) it would open the tab in a new window, but not focus on that tab if already opened.
Added the ability for it to do that.

[Chore] Sidenav External Target

---

projects/go-lib/src/lib/components/go-action-sheet/go-panel/go-panel.component.html
projects/go-style-guide/src/app/features/ui-kit/components/action-sheet-docs/components/action-sheet-panel-docs/action-sheet-panel-docs.component.html
projects/go-style-guide/src/app/features/ui-kit/components/action-sheet-docs/components/action-sheet-panel-docs/action-sheet-panel-docs.component.ts

Resolves #618 
This enables html content to be projected into a `go-panel`, thus enabling styling to be applied to panel content.

Add ability to use content-projection within go-panels

---

projects/go-lib/src/lib/components/go-file-upload/go-dragon-drop.directive.ts
projects/go-lib/src/lib/components/go-file-upload/go-file-upload.component.html
projects/go-lib/src/lib/components/go-file-upload/go-file-upload.component.scss
projects/go-lib/src/lib/components/go-file-upload/go-file-upload.component.spec.ts
projects/go-lib/src/lib/components/go-file-upload/go-file-upload.component.ts
projects/go-style-guide/src/app/features/ui-kit/components/configuration-docs/configuration-docs.component.html
projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/file-upload-docs/file-upload-docs.component.html
projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/file-upload-docs/file-upload-docs.component.ts

Resolves #577 
The "selecting" state is triggered when a user drag/drops another file onto the upload, regardless if a current file exist. If a file has already been uploaded, the new file will replace it.
Additionally, a new method has been added to the file upload to reset the state of the component to its initial state. (`reset()`)

[Chore] File Upload Enhancements

---

projects/go-lib/src/styles/_forms.scss

Resolves #654 
The label of the `go-checkbox` is positioned incorrectly:
The label is now positioned correctly:

Fix go-checkmark label position

---

projects/go-lib/src/lib/components/go-radio/go-radio-group.component.html
projects/go-lib/src/lib/components/go-radio/go-radio-group.component.spec.ts
projects/go-lib/src/lib/components/go-radio/go-radio-group.component.ts
projects/go-lib/src/styles/_forms.scss
projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/radio-button-docs/radio-button-docs.component.html
projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/radio-button-docs/radio-button-docs.component.ts
projects/go-tester/src/app/components/test-page-3/test-page-3.component.html

The current implementation of the radio button involves a legend and a fieldset, with no control over these two elements.
Resolves [639](https://github.com/mobi/goponents/issues/639)
With the introduction of two new bindings i.e. `enableLegend `and `enableFieldset`, the end user now has enough flexibility to control each of the two elements (i.e. legend and fieldset) individually.

New bindings for radio button - Issue #639

---

projects/go-style-guide/src/app/features/ui-kit/components/accordion-docs/components/accordion-panel-docs/accordion-panel-docs.component.html

When you go to the Accordion documentation, you land on the Overview sub route. Now click on the Panel option from right side of the screen, you'll notice a toast popping up at bottom right of the screen. This is unnecessary.
Resolves [662](https://github.com/mobi/goponents/issues/662)
The toast no more appears on page load when user clicks on 'Panel' option from Accordion documentation.

Removed loading test component from the first accordion titled 'Not Delayed'.

---

projects/go-lib/src/lib/components/go-side-nav/go-side-nav/go-side-nav.component.html
projects/go-lib/src/lib/components/go-side-nav/go-side-nav/go-side-nav.component.scss
projects/go-lib/src/lib/components/go-side-nav/go-side-nav/go-side-nav.component.ts
projects/go-style-guide/src/app/features/ui-kit/components/layout-docs/components/layout-nav/layout-nav.component.html
projects/go-style-guide/src/app/features/ui-kit/components/layout-docs/components/layout-nav/layout-nav.component.ts

Currently the app drawer header reads 'Switch to...', and has specific hover state styles which are not as per DSM. 
Resolves [664](https://github.com/mobi/goponents/issues/664)
Appdrawer header must read 'Launch'. Also, styles for hover state of the header are as per DSM.

Change App Drawer Read Only Text 

---

projects/go-style-guide/src/app/features/ui-kit/components/accordion-docs/components/accordion-panel-docs/accordion-panel-docs.component.html

Currently the code for the header template under accordion panel is cut off
The code section for the Header Templates Panel Docs takes up the same amount of horizontal space as the title above it

Accordion Panel Docs for Header Templates Cut Off

---

projects/go-lib/src/lib/components/go-button/go-button.component.html
projects/go-lib/src/lib/components/go-button/go-button.component.scss
projects/go-lib/src/lib/components/go-button/go-button.component.spec.ts
projects/go-lib/src/lib/components/go-button/go-button.component.ts
projects/go-lib/src/lib/components/go-button/go-split-button-option.model.ts
projects/go-lib/src/public_api.ts
projects/go-style-guide/src/app/features/ui-kit/components/button-docs/button-docs.component.html
projects/go-style-guide/src/app/features/ui-kit/components/button-docs/button-docs.component.ts

Resolves #602
Adds ability to turn a `go-button` into a split-button (only for primary and secondary button variants).

Add split-button functionality to go-button

---

projects/go-lib/src/lib/components/go-action-sheet/go-panel/go-panel.component.html
projects/go-lib/src/lib/components/go-action-sheet/go-panel/go-panel.component.ts
projects/go-lib/src/lib/components/go-side-nav/go-side-nav/go-side-nav.component.html
projects/go-lib/src/lib/components/go-side-nav/nav-app-drawer.model.ts
projects/go-style-guide/src/app/app.component.ts
projects/go-style-guide/src/app/features/ui-kit/components/action-sheet-docs/components/action-sheet-panel-docs/action-sheet-panel-docs.component.html
projects/go-style-guide/src/app/features/ui-kit/components/action-sheet-docs/components/action-sheet-panel-docs/action-sheet-panel-docs.component.ts
projects/go-style-guide/src/app/features/ui-kit/components/layout-docs/components/layout-app-drawer/layout-app-drawer.component.html
projects/go-style-guide/src/app/features/ui-kit/components/layout-docs/components/layout-app-drawer/layout-app-drawer.component.ts

Current app drawer config does not support a target for external links
Resolves https://github.com/mobi/goponents/issues/696
Optional config item added to support `target` for app drawer.

Support for 'target' element in app drawer config

---

projects/go-lib/src/lib/components/go-table/go-table-selection.model.ts
projects/go-lib/src/lib/components/go-table/go-table.component.spec.ts
projects/go-lib/src/lib/components/go-table/go-table.component.ts
projects/go-style-guide/src/app/features/ui-kit/components/table-docs/components/table-selection/table-selection.component.html
projects/go-style-guide/src/app/features/ui-kit/components/table-docs/components/table-selection/table-selection.component.ts

Resolves #684 
The `go-table` now emits an event from the `rowSelectionEvent` output when the checkbox to select/deselect all rows is clicked, rather than just when individual rows are selected/deselected.
This will enable components that need to be aware of the table's selection state when the checkbox to select/deselect all rows is clicked to do so.

Emit rowSelectionEvent when selecting or deselecting all table rows

---

projects/go-lib/src/lib/components/go-modal/go-modal.component.html
projects/go-lib/src/lib/components/go-modal/go-modal.component.spec.ts
projects/go-lib/src/lib/components/go-modal/go-modal.component.ts
projects/go-style-guide/src/app/features/ui-kit/components/modal-docs/modal-docs.component.html
projects/go-style-guide/src/app/features/ui-kit/components/modal-docs/modal-docs.component.ts

Resolves #680 
Defaults clicking outside of a modal to not close the modal. This can be changed through a binding provided on the modal.
Provides a binding on modals to individually hide the close modal icon on modals where a decision is required to be made
There are no breaking changes, but this does change the ux of how Modals work, so it should be documented here that clicking on the backdrop of a modal will no longer close it unless the `closeWithBackdrop` is set to true on the modal.

Changes to Closing Modals

---

projects/go-lib/src/lib/components/go-action-sheet/go-panel/go-panel.component.html
projects/go-lib/src/lib/components/go-action-sheet/go-panel/go-panel.component.spec.ts
projects/go-lib/src/lib/components/go-action-sheet/go-panel/go-panel.component.ts
projects/go-style-guide/src/app/features/ui-kit/components/action-sheet-docs/components/action-sheet-panel-docs/action-sheet-panel-docs.component.html
projects/go-style-guide/src/app/features/ui-kit/components/action-sheet-docs/components/action-sheet-panel-docs/action-sheet-panel-docs.component.ts

Resolves #700 
This adds a `closeOnClick` input to the `go-panel` which determines whether clicking the panel closes its parent action-sheet. The input is set to `true` by default.
This was needed because there are some cases where we do not want action-sheets to close when the `go-panel`s within them are clicked.

Add closeOnClick input to go-panel

---

projects/go-lib/src/lib/components/go-input/go-input.component.html
projects/go-lib/src/lib/components/go-input/go-input.component.spec.ts
projects/go-lib/src/lib/components/go-input/go-input.component.ts
projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/input-docs/input-docs.component.html
projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/input-docs/input-docs.component.ts

Right now, goponents does not provide a way to set maxlength and minlength for `go-input`. This PR includes necessary changes (both code-wise and documentation) for the same.
Resolves #691 
Developers can now set the maxlength and minlength for `go-input`

Max and min length bindings for goInput - 691

---

projects/go-lib/src/lib/components/go-table/go-table.component.html
projects/go-style-guide/src/app/features/ui-kit/components/table-docs/components/table-column-docs/table-column-docs.component.html
projects/go-tester/src/app/components/test-page-1/test-page-1.component.html

Currently we set the `width` property on the table cell when assigned one. That approach does not constrain the width of the column to the desired size if the content within the table is too great for its container.
Resolves #707 
Now, the `min-width` property is set instead of the `width`. This allows for stricter control over table column widths. Using `min-width` will allow the column to expand if the space is available, but it will not shrink beyond the specified limit regardless of other table content.

[Bug] Enforce Table Column Width

---

projects/go-lib/src/lib/components/go-text-area/go-text-area.component.html
projects/go-lib/src/lib/components/go-text-area/go-text-area.component.spec.ts
projects/go-lib/src/lib/components/go-text-area/go-text-area.component.ts
projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/text-area-docs/text-area-docs.component.html
projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/text-area-docs/text-area-docs.component.ts

Resolves #705 
There is the ability to pass in a maxlength on the text area

Text Area Max Length

---

projects/go-lib/src/lib/components/go-table/go-table.component.ts

The `selectAllEvent` fires twice when the checkbox is checked.
The `selectAllEvent` only fires when the value is different.

[Bug] Table: Duplicate selectAllEvents fired

---

projects/go-lib/src/lib/components/go-modal/go-modal-options.ts
projects/go-lib/src/lib/components/go-modal/go-modal.component.spec.ts
projects/go-lib/src/lib/components/go-modal/go-modal.component.ts
projects/go-lib/src/lib/components/go-modal/go-modal.item.ts
projects/go-lib/src/lib/components/go-modal/go-modal.service.spec.ts
projects/go-lib/src/lib/components/go-modal/go-modal.service.ts
projects/go-lib/src/lib/components/go-off-canvas/go-off-canvas-options.ts
projects/go-lib/src/lib/components/go-off-canvas/go-off-canvas-service.spec.ts
projects/go-lib/src/lib/components/go-off-canvas/go-off-canvas.component.ts
projects/go-lib/src/lib/components/go-off-canvas/go-off-canvas.interface.ts
projects/go-lib/src/lib/components/go-off-canvas/go-off-canvas.service.ts
projects/go-lib/src/public_api.ts
projects/go-style-guide/src/app/features/ui-kit/components/modal-docs/modal-docs.component.html
projects/go-style-guide/src/app/features/ui-kit/components/modal-docs/modal-docs.component.ts
projects/go-style-guide/src/app/features/ui-kit/components/off-canvas-docs/off-canvas-docs.component.html
projects/go-style-guide/src/app/features/ui-kit/components/off-canvas-docs/off-canvas-docs.component.ts

This PR addresses the potential for mismatched typing for both the off-canvas and modal implementations.
Currently the `openModal` method allows for `any` type to be passed in for the `component` and `bindings` properties. Additionally, the bindings for the modal itself were passed in through the `bindings` object which was originally intended to be for the bindings on the component being rendered by the modal.
Currently the `openOffCanvas` method allows for `any` type to be passed in for the `component` and `bindings` properties. Additionally the bindings for the off canvas are set through properties on the object passed into this method.
There is now partial type enforcement on the …

[Chore] Modal & Off Canvas Type Improvements

---

projects/go-lib/src/lib/components/go-datepicker/go-calendar.component.html
projects/go-lib/src/lib/components/go-datepicker/go-calendar.component.spec.ts
projects/go-lib/src/lib/components/go-datepicker/go-calendar.component.ts
projects/go-lib/src/lib/components/go-datepicker/go-datepicker.component.html
projects/go-lib/src/lib/components/go-datepicker/go-datepicker.component.ts
projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/datepicker-docs/datepicker-docs.component.html
projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/datepicker-docs/datepicker-docs.component.ts
projects/go-style-guide/src/app/features/ui-kit/ui-kit.module.ts

After clicking on the calendar icon calendar body was hiding behind of modal body.
Resolves [717](https://github.com/mobi/goponents/issues/717)
Now it's displayed on the modal body.

Add appendTo features of go-datepicker module

---

projects/go-lib/karma.conf.js
projects/go-lib/src/lib/components/go-table/go-table.component.spec.ts
projects/go-lib/src/lib/components/go-table/go-table.component.ts

Whenever the `tableConfig` of the `go-table` is assigned (or reassigned) the table subscribes to the `selectAllControl`. This results in multiple subscriptions on the single control. We watch for changes to this control and emit an event whenever it changes. This is problematic because we will emit the event for each subscription. 
This is especially problematic when pagination or sorting happens.
This moves the subscription into the `ngOnInit` so that we only subscribe to the changes once per lifetime of the table.

[Bug] Table SelectAll Subscription

---

projects/go-lib/src/lib/components/go-side-nav/go-nav-item/go-nav-item.component.spec.ts
projects/go-lib/src/lib/components/go-side-nav/go-side-nav/go-side-nav.component.html
projects/go-lib/src/lib/components/go-side-nav/go-side-nav/go-side-nav.component.spec.ts
projects/go-lib/src/lib/components/go-side-nav/go-side-nav/go-side-nav.component.ts

In mobile we have walkme-id's across a variety of elements to have a consistent way to target elements used in walk throughs. The side nav is one of those elements that we use in a variety of walkme walk throughs, but currently there isn't a way to add a custom attribute to the container.
This adds the ability to pass through an attribute into the side nav that will be added on the side nav container.

Side Nav Container Attributes

---

projects/go-lib/src/lib/components/go-modal/go-modal-options.ts
projects/go-lib/src/lib/components/go-modal/go-modal.component.spec.ts
projects/go-lib/src/lib/components/go-modal/go-modal.component.ts
projects/go-lib/src/lib/components/go-off-canvas/go-off-canvas-options.ts
projects/go-lib/src/lib/components/go-off-canvas/go-off-canvas.component.spec.ts
projects/go-lib/src/lib/components/go-off-canvas/go-off-canvas.component.ts

Resolves #744 
When the modal or off-canvas is closed their configurations are reset to their respective defaults.

[Bug] OffCanvas & Modal reset defaults on close

---

projects/go-lib/src/lib/components/go-select/go-select.component.scss

Resolves [722](https://github.com/mobi/goponents/issues/722)
1. Alignment issue when options are displaying on top under the modal popup when I have used appendTo: 'body' code.
2. Clear icon is not clickable when the selected value overlaps with the clear icon.
3. Also down arrow button overlapping with the selected value.
4. In dark theme white border color is not showing while option will display at bottom

resolve ux issues

---

projects/go-lib/src/lib/components/go-select/go-select.component.html
projects/go-lib/src/lib/components/go-select/go-select.component.scss
projects/go-lib/src/lib/components/go-select/go-select.component.ts
projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/select-docs/select-docs.component.html
projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/select-docs/select-docs.component.ts

- Drop down is always visible, regardless of if it has any items
- Drop down arrow is always visible, regardless of if it has any items
Resolves #635
Resolves #636 
- Drop down is hidden when the select is `searchable` and has items
- Drop down arrow is hidden if the select is a `typeahead` and has items OR otherwise specified through the new `hideDropDownArrow` binding
It shouldn't?

[Feature] Select Typeahead Enhancements

---

projects/go-lib/src/lib/components/go-card/go-card.component.scss
projects/go-lib/src/lib/components/go-select/go-select.component.scss
projects/go-lib/src/lib/components/go-timepicker/go-time.component.html
projects/go-lib/src/lib/components/go-timepicker/go-time.component.scss
projects/go-lib/src/lib/components/go-timepicker/go-time.component.ts
projects/go-lib/src/lib/components/go-timepicker/go-timepicker.component.html
projects/go-lib/src/lib/components/go-timepicker/go-timepicker.component.ts
projects/go-lib/src/styles/_forms.scss
projects/go-lib/src/styles/_mixins.scss
projects/go-lib/src/styles/_typography.scss
projects/go-lib/src/styles/_variables.scss
projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/forms-overview/forms-overview.component.html
projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/forms-overview/forms-overview.component.scss
projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/forms-overview/forms-overview.component.ts
projects/go-style-guide/src/app/features/ui-kit/ui-kit.module.ts

Resolves #757
- Fixes incorrect `color` values on `go-select` for light and dark themes
- Adds support for `dark` theme on `go-timepicker` (placeholder styles)
- Adds further support for content in forms with `go-form--dark` applied
- Fixes incorrect `color` values on anything using `go-input` mixin
- Adds modifier for "unstyled" `go-link`s
- Adds documentation on base `/ui-kit/forms` route in style guide for full suite of Goponents form elements

[Chore] Forms Enhancements

---

projects/go-lib/src/styles/_variables.scss

After installing v1.9.0 in an external repo, the SCSS variable in question is not formatted correctly for a production build to process it. This would not have been caught in any of our checks we have set up currently because we do not test compiling the lib project into a package, install it in a separate project, and try to compile it.
Fixes the variable to be formatted correctly.

[Bug] SCSS variable causing broken build

---

projects/go-lib/src/lib/components/go-toaster/go-toaster.model.ts
projects/go-lib/src/lib/components/go-toaster/go-toaster.service.ts
projects/go-style-guide/src/app/features/ui-kit/components/toast-docs/toast-docs.component.ts

Currently, toasts that come in from the `goToasterService` aren't dimissable. The `GoToastComponent` supports a `dismissable` input, so we should add this to the service too.
The `goToasterService` supports an additional argument, `dismissable` through the `toastInterface`.

Add 'Dismissable' argument to Toaster Service

---

projects/go-lib/src/lib/components/go-select/go-select.component.html

In the `go-select`, when `multiple` is `true` and `items` are `null` it is throwing a console error saying `cannot read property "length" of undefined".
It no longer does that

[Bug] Go-Select Multi-Select errors when "items" null

---

projects/go-lib/src/lib/components/go-table/go-table.component.html
projects/go-lib/src/lib/components/go-table/go-table.component.spec.ts
projects/go-lib/src/lib/components/go-table/go-table.component.ts
projects/go-tester/src/app/components/test-page-1/test-page-1.component.html
projects/go-tester/src/app/components/test-page-1/test-page-1.component.ts

See the issue referenced below for description of problem.
Resolves #774 
The table will handle when it becomes `selectable` after not being `selectable` and vice versa.

[Bug] Go-Table Change Selectable Issue

---

projects/go-lib/src/lib/components/go-select/go-select.component.html
projects/go-lib/src/lib/components/go-select/go-select.component.ts

Resolves #797
If `multiple` is `true` then we disable closing when an option is selected. If `multiple` is `false`, `closeOnSelect` can be set to `true` if desired.

[Chore] Select Close on Select

---

projects/go-lib/src/lib/components/go-table/go-table-config.model.ts
projects/go-lib/src/lib/components/go-table/go-table.component.ts
projects/go-style-guide/src/app/features/ui-kit/components/table-docs/components/table-overview/table-overview.component.html
projects/go-style-guide/src/app/features/ui-kit/components/table-docs/components/table-overview/table-overview.component.ts
projects/go-style-guide/src/app/features/ui-kit/components/table-docs/table-docs.service.ts

Resolves #813 
You can specify a type generic for the `GoTableConfig` interface now.

[Feature] Table Generic Typing

---

projects/go-lib/src/lib/components/go-toast/go-toast.component.html
projects/go-lib/src/lib/components/go-toast/go-toast.component.scss
projects/go-lib/src/lib/components/go-toast/go-toast.component.spec.ts
projects/go-lib/src/lib/components/go-toast/go-toast.component.ts
projects/go-style-guide/src/app/features/ui-kit/components/toast-docs/toast-docs.component.html
projects/go-style-guide/src/app/features/ui-kit/components/toast-docs/toast-docs.component.ts

Toasts do not have a max height.
Toast icons are set programmatically based on `type` binding.
Resolves #815 
Toasts now have a max height, with a new binding to provide the ability to disable the max height.
Toasts now have an `icon` binding that, when passed, will override all of the programmatically set icons for a toast.

[Feature] go-toast maxHeight & icon overrides

---

projects/go-lib/src/lib/components/go-select/go-select.component.html
projects/go-lib/src/lib/components/go-select/go-select.component.spec.ts
projects/go-lib/src/lib/components/go-select/go-select.component.ts

When a lot of results are selected, the "clear all" button appears way down the page in an unusual position.
This adds a "remove all" button at the top of the select dropdown when items are selected to allow a user to easily remove all options when lots are selected.

added remove all on select

---

projects/go-lib/src/lib/components/go-table/go-table-column.component.ts
projects/go-lib/src/lib/components/go-table/go-table.component.html
projects/go-lib/src/lib/components/go-table/go-table.component.scss
projects/go-lib/src/lib/components/go-table/go-table.component.ts
projects/go-style-guide/src/app/features/ui-kit/components/table-docs/components/table-column-docs/table-column-docs.component.html
projects/go-style-guide/src/app/features/ui-kit/components/table-docs/components/table-column-docs/table-column-docs.component.ts
projects/go-style-guide/src/app/features/ui-kit/components/table-docs/components/table-overview/table-overview.component.html
projects/go-style-guide/src/app/features/ui-kit/components/table-docs/components/table-overview/table-overview.component.ts

~~- [ ] Tests for the changes have been added~~
Resolves #811 
Added a binding to the `go-table` component called `wrapContent` that controls whether the content in all of the table cells wraps or not.
Added a binding to the `go-table-column` component called `wrapContent` that controls the content wrapping for that individual column. Note: this binding will override the `wrapContent` binding on the `go-table` for that individual column.

[Feature] go-table wrapContent

---

projects/go-lib/src/lib/components/go-action-sheet/go-panel/go-panel.component.html
projects/go-lib/src/lib/components/go-action-sheet/go-panel/go-panel.component.scss
projects/go-lib/src/lib/components/go-action-sheet/go-panel/go-panel.component.ts
projects/go-style-guide/src/app/features/ui-kit/components/action-sheet-docs/components/action-sheet-panel-docs/action-sheet-panel-docs.component.html
projects/go-style-guide/src/app/features/ui-kit/components/action-sheet-docs/components/action-sheet-panel-docs/action-sheet-panel-docs.component.ts

Resolves #817 
Matches design provided by UX

[Chore] Panel Disable Option

---

projects/go-lib/src/lib/components/go-datepicker/go-datepicker.component.spec.ts
projects/go-lib/src/lib/components/go-datepicker/go-datepicker.component.ts
projects/go-lib/src/lib/components/go-datepicker/locale-format.spec.ts
projects/go-lib/src/lib/components/go-datepicker/locale-format.ts
projects/go-tester/src/app/app-routing.module.ts
projects/go-tester/src/app/components/layout/layout.component.ts
projects/go-tester/src/app/components/test-page-4/test-page-4.component.html
projects/go-tester/src/app/components/test-page-4/test-page-4.component.ts

When picking a date (GoDatepickerComponent) in January, the field shows as invalid format
Resolves #828
The dates are validated using 0-11 for the months as described in the [MDN docs for `getMonth()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getMonth) 
The `LocaleFormat.validDate` function was changed.

[Bug] Issue #828 fix date validation

---

projects/go-lib/styles/_typography.scss
projects/go-lib/styles/_variables.scss

Added a class for unordered lists. Also added line-height to go-headings for text-wrapping
There are no common styles for `<ul>` elements
Resolves #831 
All `<ul>` moving forward will be styled the same way (using the goponent classname)

FEATURE: Added unordered list styles

---

projects/go-lib/src/lib/components/go-toast/go-toast.component.html
projects/go-lib/src/lib/components/go-toast/go-toast.component.ts
projects/go-style-guide/src/app/features/ui-kit/components/toast-docs/toast-docs.component.html
projects/go-style-guide/src/app/features/ui-kit/components/toast-docs/toast-docs.component.ts

Max height for the toast notification will not have an overflow unless specified.
Resolves #868
1. Toast notification will have the style as fit content by default.
2. To enable the scrollability behaviour `enableMaxHeight` should be set to `true`

Changes [CHORE] 868 max height for toast

---

projects/go-lib/src/lib/components/go-accordion/go-accordion-panel.component.scss
projects/go-lib/src/lib/components/go-button/go-button.component.scss

[Chore] Accordion Styling (Normal & Dark theme) #884
Resolves 884
Changed below styles
Default Accordion
Header should be equivalent to an H4 (18px - 1.125rem).
The body contains unexpected padding around the content (1.5rem top/bottom) where UX outlined in as 1rem all around.
The body text should always be 14px (0.875rem) default.
Slim Accordion
Header should be equivalent to an H5 (14px - 0.875rem).
Header section padding should be 10px (0.625rem) top and bottom and 16px(1rem) left and right
The body text should always be 14px (0.875rem) default.
The padding around the body should be 16px (1rem) all around.
Dark Theme
Follows the above rules with the following additions
Header …

884 accordion styling(normal&dark theme)

---

projects/go-lib/src/lib/components/go-button/go-button.component.scss
projects/go-lib/src/lib/components/go-hint/go-hint.component.scss
projects/go-lib/styles/_hints.scss

Secondary button, secondary split button and secondary button group were missing its border when in a disabled state.
Resolves  [872](https://github.com/mobi/goponents/issues/872)
Secondary button, secondary split button and secondary button group will have the border : 1px solid #d3d3d3 
Form hints does not match the UX approved design
Resolves  [870](https://github.com/mobi/goponents/issues/870)
Form text will be italicized and with size 12px 
Error form hints does not match the UX approved design
Resolves  [869](https://github.com/mobi/goponents/issues/869)
Error status size changed from 8px to 9px and use Horizon (#DB3939) for color and hint will be italicized

Changes_for_bugfix-872_chore-869-870_task

---

projects/go-lib/src/lib/components/go-file-upload/go-file-upload.component.ts
projects/go-lib/src/lib/components/go-text-area/go-text-area.component.html
projects/go-lib/styles/_forms.scss
projects/go-lib/styles/_typography.scss

Fixed GOP-876 uniform card margins, GOP-877 set minimum_height_for_textarea and GOP-847 file uploading component bug fix.
Resolves 
#877 
#876 
#847 
#877 - Textarea will have the minimum width as 70px.
#876 - Last child of the card content will have no margin bottom.
#847 - Reselecting the same file after clearing is working fine.

Changes_GOP-877,GOP-876,GOP-847-BUG-minimum_height_for_textarea

---

projects/go-lib/src/lib/components/go-datepicker/go-datepicker.component.html
projects/go-lib/src/lib/components/go-datepicker/go-datepicker.component.spec.ts
projects/go-lib/src/lib/components/go-datepicker/go-datepicker.component.ts

Currently we are opening calendar only on click of calendar icon inside the date field of go-date-picker.
Resolves Enhance_go-date-picker_by_enabling_calendar_to_open_when_date_field_is_clicked_anywhere_within_it
New behavior - where the calendar opens upon clicking anywhere within the date field of go-date-picker, rather than being restricted to only clicking on the calendar icon. This enhancement will significantly enhance the user experience, providing a more intuitive and seamless process for selecting dates.

[Feature] #918 enhancement of go-date-picker

---

projects/go-lib/src/lib/components/go-select/go-select.component.scss
projects/go-lib/src/lib/components/go-select/go-select.component.spec.ts

The disabled select has a background color of #F9F9F9
Resolves #924 
The disabled select background color has been changed to #F0F0F0

Update CSS for Drodown and add test cases

---

projects/go-lib/src/lib/components/go-datepicker/locale-format.spec.ts
projects/go-lib/src/lib/components/go-datepicker/locale-format.ts

Selecting date as 29 Feb for any of the date fields is throwing error across the modules
